### ISSUE TITLE
Font in Cell Error Output does not correctly display Greek letter χ

### ISSUE THREAD

**Issue by jtschneider** [fonsp/Pluto.jl#1071]
Hello guys,

Below are two quick screenshots of some output of a provoked error message that does not display correctly the actual character in use, in this case the Greek letter `χ`. As you can see, it is shown as a lowercase `x`. I suppose there is a bad font installed.

I can also copy the text from the browser, which indeed does show that the output letter is supposed to be the Greek letter `χ`
```
UndefVarError: χ not defined

    top-level scope@Local: 1

1

χ
```

![chi-error-message](https://uc7314abef1432d572e27d65bcfe.previews.dropboxusercontent.com/p/thumb/ABLUmKe5Ulg0TagNt3AO7MxNKXkpMsoc4q1QTRF6pHi94NTm-ZN_sGKCCZicVJbAiNVQT5KC-UUunlMK1UarrCRFfB69uS4elrBQl2ZsCfmL_dyNXeF3pWDWpH_gbPiPay4NZFkduk3bhpVovPpnShIGOZx3wncDxOmIuyVRonbZpeS0Ad88ftfsaLfczYATSVfCKAHkaS7O8mFGLW2-DXkRKQYx-WdE-GOzyF0M9Op2DoElK8xAV-Uh2XvvnbVw-AWwZ9VZpW0rGxvTmwmrSdDkSz0EKFybdTqh_XPhrlVE4lh5Xoa-Z3PY_jAgqMywvppZ2FoFJHfxHXsN4_Op0QHwijnvWRmvogPawR_iQLik_yAwrozewa0rt9PfUTZ3t7j0G1vtauCa6PTftyFfYyjn/p.png?fv_content=true&size_mode=5)

![x-error-message](https://uc04fc00137109bc728e64253278.previews.dropboxusercontent.com/p/thumb/ABJKkh-6LXivwjnm_HGSnnu2e0GypeymkSEu9BJLFfzbFEJrksHX9rATmVQpIzXWVQr5cbXiRxymAPGxSdo4WyI1BOx_N28zzS6o5ug0YKWmTuCNP3Wewt_XDM8T8_zyWgO-3sXy1lW7fcL0chQSHDn5RGOj7sAJDizjR5aL0senVzggALSvlNOr_hi3u963pKq6lGQoO3EDVI9TjS_q2BEBUJmZX63r5koT_iW9S2n8pPoJp_5fShvFvNsLf42FzStnrvEosNjfQLLX8Xx4eJev1h2D5XfIQgMhDWjtfAdcTYtRJWw1r0nhZL2wwyGTzOElUIkUYH82WpZr_i25-2KXX8SODbIBRD1ktbCglsE06XKGyxCrZ0hJXiPqJ-WOI8UcAkKCJS9qXEAode5mmZHB/p.png?fv_content=true&size_mode=5)

**Comment by pankgeorg** [comment]
Hello @jtschneider!!
Can you re-upload the pictures because I have trouble viewing them :( 
![image](https://user-images.githubusercontent.com/8681967/114629630-99ed0280-9cc1-11eb-9c27-e338dc534f79.png)

Also, how to you input the chi in the keyboard / What is your system?

Here in Windows 10, Greek characters work like a charm (both from Greek keyboard and latex (`\chi`) (but maybe my system is biased ;) )
![image](https://user-images.githubusercontent.com/8681967/114630071-6f4f7980-9cc2-11eb-88a5-135127259de2.png)

**Comment by jtschneider** [comment]
![Screenshot 2021-04-14 at 12 27 33](https://user-images.githubusercontent.com/9451057/114696369-ddc12580-9d1c-11eb-8db6-3533f72c3072.png)
![Screenshot 2021-04-14 at 12 27 47](https://user-images.githubusercontent.com/9451057/114696372-ddc12580-9d1c-11eb-9b0c-d2c4a506c386.png)

 Here are two more screenshots from two different browsers, Safari and Firefox on macOS v10.15.7 Catalina

**Comment by jtschneider** [comment]
Note that the issue does not arise when I correctly assign `χ`:

![Screenshot 2021-04-14 at 12 32 22](https://user-images.githubusercontent.com/9451057/114696889-7b1c5980-9d1d-11eb-873c-53a1c3d427f7.png)

**Comment by pankgeorg** [comment]
Ok now I get the issue (I haven't seen the screenshots, sorry!) Looking into it!

**Comment by pankgeorg** [comment]
Ok Just got to the bottom of this:

The problem is that the RobotoMono font has the same glyph for x and χ as you can see [here](https://fonts.google.com/specimen/Roboto+Mono?preview.text=%CF%87x&preview.text_type=custom).

I don't know if that's a good enough reason to change the font.

You can confirm that χ is indeed χ by copying and pasting it anywhere with a different font.

if you want to stop using `RobotoMono`, you can add the following cell somewhere in your notebook:

```
html"""
<style>jlerror {
	font-family: monospace;
}
"""
```

**Comment by jtschneider** [comment]
Such a shame!
Actually I would like to propose a change of font in that case.
The Fira Mono font is published under the SIL Open Font License by Mozilla and can be found in its repository [here](https://github.com/mozilla/Fira).
I find reading Fira Mono pleasing to the eye and it certainly help when debugging code where you defined x and χ as variables....!
Fira Mono is also available on [Google Fonts](https://fonts.google.com/specimen/Fira+Mono?preview.text=%CF%87x&preview.text_type=custom&category=Monospace#standard-styles).
