### ISSUE TITLE
updating default() in Plots does not update the plots

### ISSUE THREAD

**Issue by lmiq** [fonsp/Pluto.jl#1095]
If one sets a cell with, for example:

```
default(framestyle=:box,label="",linewidth=2)
```

and have some plot afterwards, updating the linewidth, for example, does not update automatically the plot styles.

Minimal set of cells:

```
using Plots
default(framestyle=:box,label="",linewidth=2)
plot(rand(10),rand(10))
```

**Comment by fonsp** [comment]
That's because it is a _sateful mutation_, hidden from Pluto, see #564 #316. You might want to file an issue with Plots.jl to change their API into something without this state problem, but I doubt that it's possible without changing the API drastically.

I would suggest something like:

```julia
plot = Plots.generate_plot_method(framestyle=:box,label="",linewidth=2)
```

Then you make the dependency explicit, and you can have multiple plot styles in parallel:

```julia
plot = Plots.generate_plot_method(framestyle=:box,label="",linewidth=2)
thickplot = Plots.generate_plot_method(framestyle=:box,label="",linewidth=10)
```
