### ISSUE TITLE
Markdown centers an equation if it's in the beginning of a line.

### ISSUE THREAD

**Issue by xijiang** [fonsp/Pluto.jl#1127]
For example:

- $a$ blah, blah

$a$ will be centered. `blah, blah` will be put in the next line.

This is making it difficult to make this equation inline.

**Comment by holomorphism** [comment]
Using ` ``...`` ` instead of `$...$` or putting an extra space at the beginning of the line seems to solve this problem. (` ``...`` ` is recommended)

![image](https://user-images.githubusercontent.com/3076585/116498585-07fe1000-a8e5-11eb-842f-809aab3a2751.png)

Some problems have been pointed out with Markdown parsing, but these are problems with Markdown.jl in julia, not pluto. Some of these issues may be resolved in the future when CommonMark.jl is adopted by julia or pluto. (#956)
