### ISSUE TITLE
Offline use of Pluto

### ISSUE THREAD

**Issue by wulpuqu** [fonsp/Pluto.jl#1132]
Hello everyone,

I am trying to use Pluto on an offline machine to write notebooks.  But unfortunately, the edition of notebook is impossible.

After `Pluto.run()`, it starts the default browser (here Firefox v78.5) and the browser prints the home page. It takes a fairly long time since some `.js` scripts need to be loaded from `cdn.jsdelivr.net`. Clicking on `create notebook`, gives a blank page after waiting for firefox to fail all `.js` scripts queries from `cdn.jsdelivr.net`.

Could it be possible that Pluto.jl comes with these java scripts instead of reaching for it on the web ? I am not very familiar with Web development but if it is possible this feature will allow users to use Pluto.jl on offline computers.

Edit: With Pluto v0.14.3, Firefox v78.5 on a Linux Debian machine.

**Comment by Pangoraw** [comment]
This is related to #241

**Comment by joshday** [comment]
For anyone wanting a quick solution to this, [here is a script](https://gist.github.com/joshday/1881c2bb7c781027bfcb0c598de0f8b5) that will edit Pluto's frontend files to use local assets instead of a CDN.

WARNING: It directly modifies Pluto's files, so I'd recommend instantiating your project in a separate depot.  See instructions at the top of the gist.
