### ISSUE TITLE
Code behavior depends on what a variable is named.

### ISSUE THREAD

**Issue by konstantin-azarov** [fonsp/Pluto.jl#1146]
Hi all,

Here's a strange bug I came upon yesterday. This code works fine:

```### A Pluto.jl notebook ###
# v0.14.5

using Markdown
using InteractiveUtils

# ╔═╡ 295226a8-ae06-11eb-19bd-cd3efe386dc2
using Rotations

# ╔═╡ 6b020be0-ae06-11eb-3c30-2f3699d495ee
rottt = RotYXZ(1, 2, 3.0)

# ╔═╡ 31b5450a-ae06-11eb-281b-838d12bcfb6f
rot1 = MRP(1.0, 0.0, 0.0)


# ╔═╡ 34295c22-ae06-11eb-3020-b36ba2a299b8
let q1 = Quat(rottt), q2 = Quat(rot1)
	(q1, q2)
end

# ╔═╡ Cell order:
# ╠═295226a8-ae06-11eb-19bd-cd3efe386dc2
# ╠═6b020be0-ae06-11eb-3c30-2f3699d495ee
# ╠═31b5450a-ae06-11eb-281b-838d12bcfb6f
# ╠═34295c22-ae06-11eb-3020-b36ba2a299b8
```

Output:
![image](https://user-images.githubusercontent.com/4876666/117335142-0d64d880-ae58-11eb-93a5-2398592ec4c5.png)

However, if I change the name of `rottt` to `rott`, it fails:
![image](https://user-images.githubusercontent.com/4876666/117335250-2ec5c480-ae58-11eb-885a-fab7c73ac6d5.png)

Weirder still, if `q1` and `q2` are computed in different cells, everything is fine:
![image](https://user-images.githubusercontent.com/4876666/117335343-4ac96600-ae58-11eb-99b8-13542d00d393.png)

I guess it is some sort of a bug in the reactive machinery? Any suggestions on where to look?

**Comment by fonsp** [comment]
@Pangoraw any ideas?

**Comment by fonsp** [comment]
The issue is indeed caused by the Rotations.jl bug shown in the example by @ariekahn https://github.com/fonsp/Pluto.jl/issues/1146#issuecomment-839343698 . Be sure to report it to Rotations.jl. 

---

It happened in Pluto because this line **creates a vector** from the variables referenced in the cell:

https://github.com/fonsp/Pluto.jl/blob/25ece1df1d8de003c9c21538924baecec7b70679/src/runner/PlutoRunner.jl#L123

The fact that the behaviour depends on the choice of symbol is due to the ordering of `Set`s, which uses the hash of each element to order them, so a change to one symbol name can flip their order:

```julia
julia> Set([:rottt, :rot1])
Set{Symbol} with 2 elements:
  :rot1
  :rottt

julia> Set([:rott, :rot1])
Set{Symbol} with 2 elements:
  :rott
  :rot1
```

We use `Set` as the data structure for referenced variables.
