### ISSUE TITLE
Ctrl+Click on variable with !

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#1178]
I understand that non-latin characters are tricky, but can you find a way to make variable names like `push!` clickable? @pankgeorg

**Comment by pankgeorg** [comment]
Found the bug: document.querySelector doesn't like exclamation marks: `Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#push2!' is not a valid selector.`. That's weird, because the [HTML standard](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute) is supposed to allow it.

non-latin characters should work fine, as we do `encodeURI` on all names
