### ISSUE TITLE
Feature request: Pluto working with Brave browser

### ISSUE THREAD

**Issue by marcello-pietrobon** [fonsp/Pluto.jl#1189]
Hello Pluto's team,

Feature request:
is ti possible to have Pluto work with Brave browser?

it never works with Brave, though with Chrome sometimes it does
(but see https://github.com/fonsp/Pluto.jl/issues/1188)

Thank you.

**Comment by marcello-pietrobon** [comment]
I've just discovered that is a firewall problem. I'm using WinPrivacy which is a per-application firewall.
so maybe this becomes a question, that is, **what kind of application should I enable in such firewall for Pluto to work with the browser?**

**Comment by pankgeorg** [comment]
Hello @marcello-pietrobon!

This is not anything specific to Pluto.

Pluto has a web-server to which you connect with a browser. Your browser must be allowed to access the ports of the webserver (1234 by default, but you can also try others, like port 80 - which - most likely - will be open).

Because this is not pluto-related, I'm closing this issue!

Thanks for being around this place of the internet!
