### ISSUE TITLE
Collapsible typeparameters

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#122]
For long stacktraces like they happen for example for 

```[1,2]*[1,2]```

it would be nice if the type parameters where displayed as some collapsed `SomeType{>...}` where you could show or hide the complete parameter list by clicking the arrow.

For example implementing
```
function Base.show(io::IO, ::MIME"text/html", x::DataType)
        show(io, x.name)
	if length(x.parameters) > 0
		print(io, "{")
		print(io, """<jltree class="collapsed" onclick="onjltreeclick(this, event)">""")
    	        print(io, "<jlarray>")
    	        Pluto.PlutoRunner.show_array_row.([io], enumerate(x.parameters))
    
    	        print(io, "</jlarray>")
    	        print(io, "</jltree>")
		print(io, "}")
	end
end
```
already displays types that are the result of a cell almost like I imagine. However:
1. it does not work for stacktraces and
2. the parameter list is not really collapsible but is always displayed in full, just the format is changed by clicking the arrow.

If you can give me some hints on how to solve these two issues I could try to implement some PR for this.

**Comment by fonsp** [comment]
For reference, [this](https://user-images.githubusercontent.com/6933510/82835048-2da7bb80-9ec3-11ea-9e84-ad8f4d94db82.png) is what the error message currently looks like.

**Comment by fonsp** [comment]
Wow that's a cool suggestion!

Copy pasting your code into a notebook does not change the error message for me. Where do you define the custom `show` method?

1. Could you also give an example that shows a useless stacktrace? I am surprised that it does not work, that would mean that `show` is not used by Julia to convert the datatype to a string in the stack frame `show` process.
2. I'm not able to verify, but it sounds like it is _wrapping_ the list into multiple lines, right? You could either disable wrapping, or hide all elements when the list is collapsed. This is done using CSS; you need to change something to the DOM generation (the code you wrote) to be able to differentiate this case from normal arrays - maybe add a class `parameter-list` to `<jltree>`.

You can try out new CSS rules inside your notebook:
```
html"""
<style>
jltree.parameter-list {
    color: purple;
}
</style>
"""
```

or add them to `treeviewer.css` and refresh.

I think that the nicest solution would be to give a custom `showerror` method for `MethodError` so that it also uses the custom formatting of stack traces. This also requires some work on the front-end - right now it does the formatted display only for the _stack trace_. I could give you some more info about this if you like!

Once they are both shown using the same method, implementing the collapsible types would be pretty much like you described!

**Comment by karlwessel** [comment]
I only tested the `show` method with the return value of cell with something like `typeof([[1,2]])`.

The complete Error (Message and stacktrace) is unaffected by this. I think julia uses `show_type` directly instead of show. Don't know why.

What do you mean with an example for a useless stacktrace?

Thanks for the hints regarding the javascript, I'll play around with it the next time I want to procrastinate instead of doing my exercises :).

**Comment by fonsp** [comment]
Alright!

Maybe I'm confused, could you clarify 1. in your original post?

**Comment by karlwessel** [comment]
Ok, this probably is the reason why one should always provide a MWE :). Here is one that should make things clearer:
```
### A Pluto.jl notebook ###
# v0.9.2

using Markdown

# ╔═╡ eeb47356-9e80-11ea-2175-017970c591d7
using Pluto

# ╔═╡ 4ad78a58-9fd8-11ea-06b7-efaca6ce4431
md"This displays the parameters of types as a collapsible list"

# ╔═╡ 80d051d6-9e7e-11ea-077c-37e9ba21e35c
function Base.show(io::IO, ::MIME"text/html", x::DataType)
    show(io, x.name)
	if length(x.parameters) > 0
		print(io, "{")
		print(io, """<jltree class="collapsed" onclick="onjltreeclick(this, event)">""")
    	print(io, "<jlarray>")
    	Pluto.PlutoRunner.show_array_row.([io], enumerate(x.parameters))
    
    	print(io, "</jlarray>")
    	print(io, "</jltree>")
		print(io, "}")
	end
end

# ╔═╡ 5d5b556a-9fd8-11ea-0292-c578eb0d4e6f
md"The display of collapsible types works if the result of a cell is a type:"

# ╔═╡ 7a3540c4-9f15-11ea-010a-4f484a7dc394
typeof([[1,2]])

# ╔═╡ 879d2d4e-9fd8-11ea-16a7-bf58bd628baf
md"It however does not work yet when an error is displayed, neither in the error message itself nor the stacktrace:"

# ╔═╡ 8361cbfc-9f14-11ea-0b26-01f1d5ce748f
function test(a)
	throw(InexactError(:test, typeof(a), a))
end

# ╔═╡ 9156565c-9f14-11ea-1caa-7766aaa97bc5
test([[1,1]])

# ╔═╡ Cell order:
# ╠═eeb47356-9e80-11ea-2175-017970c591d7
# ╟─4ad78a58-9fd8-11ea-06b7-efaca6ce4431
# ╠═80d051d6-9e7e-11ea-077c-37e9ba21e35c
# ╟─5d5b556a-9fd8-11ea-0292-c578eb0d4e6f
# ╠═7a3540c4-9f15-11ea-010a-4f484a7dc394
# ╟─879d2d4e-9fd8-11ea-16a7-bf58bd628baf
# ╠═8361cbfc-9f14-11ea-0b26-01f1d5ce748f
# ╠═9156565c-9f14-11ea-1caa-7766aaa97bc5
```

**Comment by karlwessel** [comment]
But anyway: I think I will be able to make this work once I get some free time. The major problem was the Javascript part which you already helped with. Getting through calltraces for displaying error messages is easier :).

**Comment by karlwessel** [comment]
I am currently working on getting the interactivity for the error message part of the error to work. For that I modified [line 208 of runner/PlutoRunner](https://github.com/fonsp/Pluto.jl/blob/de637fbc8fd57b93bc8f0d78dbe31fcb3b5cb27d/src/runner/PlutoRunner.jl#L208) to
```
sprint(json, Dict(:msg => sprint(showerror, MIME"text/html"(), val.ex), :stacktrace => pretty)), MIME"application/vnd.pluto.stacktrace+json"()
```

It seems like this is not enough to get the following test notebook to work:

```
### A Pluto.jl notebook ###
# v0.9.2

using Markdown

# ╔═╡ 07dfd394-a349-11ea-31d1-89b38d5cc78f
struct TestError <: Exception end

# ╔═╡ 8977b34a-a1be-11ea-2d2d-47dc94b89da3
begin
	"""Fallback for any non html error"""
	Base.showerror(io::IO, mime, err) = showerror(io, err)
	
	function Base.showerror(io::IO, ::MIME"text/html", ex::TestError)
		print(io, "My TestError: ")
		show(io, MIME"application/vnd.pluto.tree+xml"(), [1,2,3])
	end
end

# ╔═╡ 36eca786-a349-11ea-00e0-8d9bab738585
throw(TestError())

# ╔═╡ 3d771b74-a34a-11ea-104c-29b68094a3bf
throw(ErrorException("test"))

# ╔═╡ Cell order:
# ╠═07dfd394-a349-11ea-31d1-89b38d5cc78f
# ╠═8977b34a-a1be-11ea-2d2d-47dc94b89da3
# ╠═36eca786-a349-11ea-00e0-8d9bab738585
# ╠═3d771b74-a34a-11ea-104c-29b68094a3bf
```

When trying to show an interactive view of an array in the error message part of `TestError` in cell three it displays

```
My TestError: Int64

12233
top-level scope@Local:1
top-level scope@Parse.jl:91
(::Distributed.var"#101#102"{Distributed.CallMsg{:call}})()@process_messages.jl:290
run_work_thunk(::Distributed.var"#101#102"{Distributed.CallMsg{:call}}, ::Bool)@process_messages.jl:79
run_work_thunk(::Distributed.RemoteValue, ::Function)@process_messages.jl:88
(::Distributed.var"#94#96"{Distributed.RemoteValue,Distributed.var"#101#102"{Distributed.CallMsg{:call}}})()@task.jl:358
```

Those `12233` after the error message should not be there and it seems like the html code for the array got mangled somehow since the array also is not displayed correctly. You said I would have to change some things on the frontend part?

**Comment by karlwessel** [comment]
Small update: it works when I set `usehtml=false` in
```
function show_array_row(io::IO, pair::Tuple)
    i, el = pair
    print(io, "<r><k>", i, "</k><v>")
    show_richest(io, el; onlyhtml=false)
    print(io, "</v></r>")
end
```

**Comment by fonsp** [comment]
(I'll get back to this soon!)

**Comment by karlwessel** [comment]
That would be good, because at the moment I can't even convince Pluto to render any html inside an error. Any html is just rendered as is and not interpreted as html.

**Comment by fonsp** [comment]
I can give the first part of my answer right now:

How error printing currently works is:
1. [`format_output` is dispatched on a `CapturedException`](https://github.com/fonsp/Pluto.jl/tree/v0.9.9/src/runner/PlutoRunner.jl#L199)
2. This method will [send a JSON-serialized object, and the improvised MIME type `application/vnd.pluto.stacktrace+json` to the front-end](https://github.com/fonsp/Pluto.jl/tree/v0.9.9/src/runner/PlutoRunner.jl#L216). This object contains [stack trace details](https://github.com/fonsp/Pluto.jl/tree/v0.9.9/src/runner/PlutoRunner.jl#L208-L215) and the error message as string `sprint(try_showerror, val.ex)`. 
3. The front-end receives this object+MIME and [creates an `ErrorMessage` component](https://github.com/fonsp/Pluto.jl/tree/v0.9.9/assets/components/CellOutput.js#L64). 
4. If the error message is not one of [the special ones](https://github.com/fonsp/Pluto.jl/tree/v0.9.9/assets/components/ErrorMessage.js#L40-L54), it [splits on `\n` and turns each line into an HTML `<p>` element](https://github.com/fonsp/Pluto.jl/tree/v0.9.9/assets/components/ErrorMessage.js#L57). (This escapes HTML syntax, which is why custom HTML no longer works.)

Part 2 in a bit

**Comment by karlwessel** [comment]
At which step does the escaping take place? I went through the code and could not find it at step 4.

**Comment by fonsp** [comment]
Escaping is part of the functionality of `html`/React. (Since the rewrite last week.)

So the easiest way would be to leave the Julia side as-is, and add a new special error pattern in 4. that looks for `MethodError` and `Closest candidates are:`. 

You could make the candidate lines `<p style="white-space: nowrap;">` instead of `<p>`, that would simply limit a candidate line to one line, and the user can scroll the error message horizontally if they want to know more. You would also have this when using `<jltree>`, because `<jltree>` shows the same number of elements whether expanded or not.

**Comment by fonsp** [comment]
Sorry the links in 4. were wrong, have a look at the edited version

**Comment by fonsp** [comment]
Doing it in the front-end also keeps the project clean - error rewrites still only happen on the front-end in an organised way.

**Comment by karlwessel** [comment]
Hmm, my original idea was to basically display everything in curly brackets collapsed by default. So that for example 
```
somefunction(a::Array{Array{SomeStrangeType{Int}, 2}, 10}, b::Int)
```
gets rendered as
```
somefunction(a::Array{...}, b::Int)
```
where you can click on the dots to expand the actual type parameters. 
That already workes for cell outputs, and before the frontend rewrite also for error messages. But I did that on julia side. 

Now it really seems like I have to learn javascript xD.

**Comment by fonsp** [comment]
Oh that's cool... but let's limit ourselves to the MethodError for now? I feel like collapsible DataTypes are mostly useful inside that error (and PlutoRunner.jl should stay 'minimal').

So I would say, first make it render `<p style="white-space: nowrap;">` instead of `<p>` inside the error, and later you could write a curly bracket matcher for JS to make it collapsible dots.

But save the `show` method that you wrote for later!

**Comment by karlwessel** [comment]
That sounds much less cooler but terribly reasonable ... fine :-).

**Comment by fonsp** [comment]
JS is really fun though, I promise!!
