### ISSUE TITLE
Open multiple notebooks at start and without browser

### ISSUE THREAD

**Issue by lungben** [fonsp/Pluto.jl#1278]
You can open a default notebook with the Pluto option
`Pluto.run(notebook="test.jl")`

Especially when using Pluto as a REST Server (with https://github.com/fonsp/Pluto.jl/pull/1052 ) it would be good to have the possibility to start multiple notebooks from the command line.

Suggested syntax:
`Pluto.run(notebook=["test.jl", "test2.jl"])`

Currently, the opening of a notebook works by passing the path to the browser (e.g. http://localhost:1234/open?secret=r6d46b55&path=test.jl). However, this only works when a browser is actually opened, which may not be the case if Pluto is used as a REST server. It would be good to have a way to open a notebook on server side only, without browser.

**Comment by fonsp** [comment]
Currently, `notebook` is part of our configuration, but that is a bit strange (since it depends on the location where you launch pluto).

We should remove it from the Configuration and instead add it as kwarg to `Pluto.run`.

Then we add two kwargs, `notebook` and `notebooks` (for backwards compat) and we do:

`[notebook, notebooks...]`

or multiple dispatch :))
