### ISSUE TITLE
Sending statistics: opt-in instead of opt-out

### ISSUE THREAD

**Issue by fbanning** [fonsp/Pluto.jl#129]
I had a look at the statistics page and while I understand the interest in how people use Pluto, I also believe it might be sensible to send statistics on an opt-in basis instead of opt-out as it currently is.

Setting the checkbox to off by default might introduce the problem that not many users will send their statistics in the end because they never have a look at the statistics settings. This could be solved by introducing a welcome dialogue after first start of Pluto, asking users if they agree on sending usage data to the Pluto devs.

**Comment by fonsp** [comment]
Hi!

Thanks for your suggestions about statistics collection! This can be a tricky subject, which is why I have tried my best to make statistics collection as transparent as possible, for example by showing users the raw stats message.

It sounds like you understand my reasons for implementing statistics, and I agree with your point that it should be opt-out! I will correct this in `v0.9.3`. 

Thanks!

**Comment by fbanning** [comment]
Thanks for your consideration! I understand that these statistics might be helpful and it can clearly be seen that you have thought about how to make this as transparent as possible. The raw stats message is indeed very nice and I appreciate it (as do others as well, I suppose).

> I agree with your point that it should be opt-out

This is most likely a typo but I have suggested to make data collection *opt-in* (i.e. it is off by default and users have to agree on sending data) *instead of opt-out* as currently (i.e. it is on by default and user have to refuse sending data).

**Comment by fonsp** [comment]
Whoops, I meant `opt-in`!
