### ISSUE TITLE
Reduce interval in which statistics are sent

### ISSUE THREAD

**Issue by fbanning** [fonsp/Pluto.jl#130]
In the spirit of data reduction and data economy, I want to suggest that Pluto cuts down on data collection of its users. Currently user statistics are sent every 10 minutes, according to the statistics page within Pluto.

This is a bit too often and seems excessive, especially considering the rather long duration most users will have Pluto opened when they work on their projects (jumping back and forth between official docs, discourse, SO, internal documents, actual code, etc.). I guess that tracking usage on such a regular basis might not generate any insights necessary for the development of Pluto (please correct me if I'm wrong).

My suggestion would be to increase that interval to 30 or even 60 minutes. Another option would be to make it a bit more sophisticated/dynamic, e.g. send statistics every time a new file is opened and then once again when it's closed.

**Comment by fonsp** [comment]
I did consider data usage when choosing a time interval, but my conclusion was actually the opposite from yours: The average statistics message is only about `1kB`, which is sent using a single HTTP request. For comparison: an average SO page is about `50kB` with caching, `400kB` without, across multiple HTTP requests - these are usual values for web pages with mostly text and markup.

For this reason, I decided that 10 minutes is long enough to have negligible data usage, while still being representative of overall notebook usage, _including quick experiments_, which is exactly what Pluto is trying to encourage!

Having a fixed time interval is important because this way, the stats messages are representative of a fixed amount of usage (no matter _what kind of_ usage). If the timing was dynamic, this could only be achieved by including a way to identify multiple stats messages from the same user, but it is more important for the statistics messages to be anonymous.

For the same reason, the _first_ statistics message should be sent after the same amount of time as the _second_ message, so that they both represent the same amount of usage. The statistics message also includes a `hasFocus` boolean, to record whether the notebook tab was in focus at the moment of collecting stats.

I hope this clarifies my reasoning behind the 10 minute interval - what do you think?

**Comment by fbanning** [comment]
I'm actually less concerned about the size of the data that is sent (e.g. 1kB of statistics). I think it's a reasonably small file size and should not be a problem for anyone (not even users using limited mobile data connections or similar).

I think I understand your reasoning behind using a fixed time interval. There's nothing fundamentally wrong with wanting to have a consistent set of usage data to analyse. Still, I'm unsure whether data collection every 10 minutes yields better insight into Pluto usage than for example every 30 minutes. The answer to this is highly dependant on what is actually done with the data (i.e. depends on the kind of analyses).

I would just argue that creating a dataset including a *user's direct momentary interaction with Pluto* (e.g. `hasFocus`) is somehow more delicate and debatable than collecting *generalised data on usage of Pluto* (e.g. `numCells`, `numMarkdowns`, `versionPluto`) which can clearly be considered metadata for steering the development process. Furthermore, I personally dislike the collection of a `timestamp` as analysis of this field might convey a lot of inherent information about the user (see sidenote below). All of these thoughts should be kept in mind for future changes of the statistics collection.

(Sidenote: Without going too much into detail about the amount/types of data collected (which is pretty reasonable as far as I could see), I want to note that the users cannot be fully sure of anonymous collection of data because each http request (sending data in this case) could generally be linked to the user's IP. I know that this is a touchy topic, so I will refrain from bringing this into the discussion of time intervals, it's just that I wanted to mention it as well because I was just thinking about it a moment ago.)

**Comment by fbanning** [comment]
After thinking about it a bit more, maybe it's possible to change the whole procedure itself:

- Statistics are collected in one *local* file that is directly related to the current Pluto session.
- New data is collected every x minutes while Pluto is running. This could be 10, 30 or 60 minutes, whatever you find appropriate for your analysis purposes. This new set of data is then added to the end of the session statistics file.
- Session statistics file is then sent as a whole at a fixed point in time (e.g. on next startup of Pluto).

Doing it like this might allow to omit the collection of the `timestamp` field in the statistics file because the fixed data collection interval would ensure that every new dataset is indeed time consistent. The need for absolute timestamps (i.e. at which exact time each new dataset is created) could be dropped because session data would be serialised locally on the user machine instead of on your server.

**Comment by malyvsen** [comment]
Okay, so after a lot of internal discussion we decided that we are making the statistics system _opt-in_ (as discussed in #129), and leaving the stats message as it is. The way we see it, the important thing is that users know exactly what they are contributing - and if they prefer us not knowing how many cells they have, they don't have to let us know.

Not changing the stats message helps us in two ways:
* making the collection code more complicated also makes it harder to reason about, which makes it less transparent!
* we're a very small group making Pluto in our free time, and we need to focus on the project's main goals and user requests.

Note: The statistics message, as seen in Pluto, is actually everything we use: the data is sent to Google Firebase, which [does not store your IP address for more than a few days](https://firebase.google.com/support/privacy), and HTTP metadata is never accessible to us.
