### ISSUE TITLE
Assignment to image pixels does not update the image via dependencies

### ISSUE THREAD

**Issue by pjgoodall** [fonsp/Pluto.jl#1318]
Following along, and writing my own version of the code in Grant Sanderson's '[Working with images in Julia](https://youtu.be/DGojI9xcCfg?t=619)', I'm finding that when I loop through updating pixels in an image referenced by a variable, the cell referencing the variable for display is not updated. I seems pretty clear that an operation is changing the variable. 

I expect the image to be updated through variable dependency - and it isn't.

I've attached a copy of my Pluto notebook.
[notebook.zip](https://github.com/fonsp/Pluto.jl/files/6819276/notebook.zip)

**Comment by Pangoraw** [comment]
Hi!
Reactivity is disabled for assignments to fields or indices because mutating a variable can create ambiguous dependency graphs (if two cells mutate a variable, which one should run first?). You can take a look [at the wiki](https://github.com/fonsp/Pluto.jl/wiki/%E2%9A%A1-Writing-and-running-code) (section "How can I modify a variable in a different cell?") for solutions.

**Comment by pjgoodall** [comment]
OK, thanks very much. I thought it must be by-design. Dependencies/constraints ain't easy. 🙂
