### ISSUE TITLE
Base.@kwdef redefinition error with types following Unitful.jl documentation

### ISSUE THREAD

**Issue by disberd** [fonsp/Pluto.jl#1388]
When trying to update a struct created using Base.@kwdef following the guidelines of the [Unitful.jl documentation](https://painterqubits.github.io/Unitful.jl/dev/highlights/#Dimensions-in-a-type-definition), there is an error in Pluto.

![image](https://user-images.githubusercontent.com/12846528/129211598-564a7d08-a35c-489e-ae70-7e6754e6ca19.png)

This is in all likelihood very similar to https://github.com/fonsp/Pluto.jl/issues/1338 so hopefully the solution is also similar.

Edit: Tagging @Pangoraw to confirm if it is indeed similar to https://github.com/fonsp/Pluto.jl/issues/1338

**Comment by disberd** [comment]
It seems that directly putting the variables exported with Unitful.DefaultSymbols does solve the error upon redefinition, though it would still be nice to have this work either way.

Here is the different outputs of the `sanitize_expr`:

![image](https://user-images.githubusercontent.com/12846528/129215636-fb48b913-6c43-42aa-b222-4f65055e16b2.png)

**Comment by Pangoraw** [comment]
Good catch, thanks! 
This is due to a set of macros being expanded on the Pluto process to avoid sending message to the notebook process but the expansion fails because there are unknown macros in the expression. Some macros like `@kwdef` and `@cmd` should probably be removed from this list.

https://github.com/fonsp/Pluto.jl/blob/1dd23a2431b3c3ff56871eca4ada7a425805c196/src/analysis/ExpressionExplorer.jl#L758-L759
