### ISSUE TITLE
Waiting for terminal input leads to error on the notebook UI

### ISSUE THREAD

**Issue by Oblynx** [fonsp/Pluto.jl#1394]
I tried to follow a [FastAI.jl tutorial](https://fluxml.ai/FastAI.jl/dev/docs/data_containers.md.html) on a Pluto notebook. First step is to download a dataset as a data dependency.

Since it doesn't already exist in my environment, if I were calling it from the REPL, the function call creates a terminal prompt to ask [y/n] if it should fetch it. The same is shown at Pluto's logs, repeated [1].

The Pluto UI shows an `IOError: Could not open stream` [2]. Is it possible for Pluto to redirect stdin to a prompt created on the UI?

#### [1] Pluto logs

```
      From worker 3:	This program has requested access to the data dependency fastai-imagenette2-160.
      From worker 3:	which is not currently installed. It can be installed automatically, and you will not see this message again.
      From worker 3:	
      From worker 3:	"imagenette2-160" from the fastai dataset repository (https://course.fast.ai/datasets)
      From worker 3:	
      From worker 3:	
      From worker 3:	
      From worker 3:	Download size: ???
      From worker 3:	
      From worker 3:	
      From worker 3:	
      From worker 3:	Do you want to download the dataset from https://s3.amazonaws.com/fast-ai-imageclas/imagenette2-160.tgz to "/home/jovyan/.julia/datadeps/fastai-imagenette2-160"?
      From worker 3:	[y/n]
...
<repeats>
```

#### [2] Pluto UI error

Cell input:
```
> dir = datasetpath("imagenette2-160")
```

Cell output:
```
IOError: Could not open stream.

better_readline(::Base.PipeEndpoint)@util.jl:57
better_readline()@util.jl:55
input_choice(::String, ::Char, ::Vararg{Char, N} where N)@util.jl:82
input_bool@util.jl:70[inlined]
check_if_accept_terms(::DataDeps.DataDep{String, String, typeof(DataDeps.fetch_default), typeof(DataDeps.unpack)}, ::String, ::String)@resolution_automatic.jl:180
accept_terms@resolution_automatic.jl:163[inlined]
var"#download#13"(::String, ::Nothing, ::Bool, ::typeof(download), ::DataDeps.DataDep{String, String, typeof(DataDeps.fetch_default), typeof(DataDeps.unpack)}, ::String)@resolution_automatic.jl:72
download@resolution_automatic.jl:70[inlined]
handle_missing@resolution_automatic.jl:10[inlined]
_resolve(::DataDeps.DataDep{String, String, typeof(DataDeps.fetch_default), typeof(DataDeps.unpack)}, ::String)@resolution.jl:83
resolve(::DataDeps.DataDep{String, String, typeof(DataDeps.fetch_default), typeof(DataDeps.unpack)}, ::String, ::String)@resolution.jl:29
resolve(::String, ::String, ::String)@resolution.jl:54
resolve(::String, ::String)@resolution.jl:73
datasetpath(::String)@load.jl:11
top-level scope@Local: 3[inlined]
```

**Comment by fonsp** [comment]
We don't/won't support terminal input: https://github.com/fonsp/Pluto.jl/discussions/765

Consider contacting the authors of your tutorial to improve the experience on terminal-less environments.

**Comment by oxinabox** [comment]
FYI. From the other side.

As the author of DataDeps.jl: a package which is much older than Pluto and long ago hit feature completeness and ceased to get changes because it is done.
We very intentionally do use terminal input; as the lowest common denominator.
Other tools (that were popular when DataDeps was created) like Juno and Jupyter, do redirect calls to `read` on `stdin` into input boxes.
We need to do so, because it is required for some datasets that the user agrees to terms and conditions before downloading.
And we consider it important to be able to present authorship details on datasets, which can be major undertakings to create; and generally must be credited in academic work building upon it.
More generally, we need to make sure people understand what they are downloading.
As much as I do respect Pluto's opinionated take, which is backed up with good reasons, DataDeps here also has an opinionated take backed up with good reasons.


Anyway, happily there is a nice and easy (if a bit ugly) way to work around this.
If you set the `DATADEPS_ALWAYS_ACCEPT` environment variable to `"true"` or similar it will not ask for user input.
E.g. adding `ENV["DATADEPS_ALWAYS_ACCEPT"] = "true"` to top of your notebook.

**Comment by Oblynx** [comment]
Very nicely put. Maybe a third package can extend Pluto to provide std{in,out} redirections, making this a third opinion that brings everything together without prejudice. I haven't looked into whether it's feasible.
