### ISSUE TITLE
Saving Pluto notebooks as static HTML in Safari saves them as `true.html`

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1424]
When I save any of my notebooks as HTML in Safari, the output file is _always_ called `true.html`. The name of the output file is correct in Chrome, though.

- MacOS 10.15.7
- Safari 14.1.2
- Pluto v0.15.1
- Julia 1.7.0-beta3.0

**Comment by ForceBru** [comment]
BTW, in my experience, this started working correctly somewhere before Pluto 0.17.4, but now I'm getting `true.html` again...

**Comment by lucifer1004** [comment]
I believe this is because the fix [752fa6e](https://github.com/lucifer1004/Pluto.jl/commit/752fa6ecdaefb2d3dac248a4ca886eb7c214ae0f#diff-4f34fa1bdbc35f16f0c5e95699d9a980d0146101f1608f372e03114870835e8f) was reverted unintendedly in [8aefef1](https://github.com/lucifer1004/Pluto.jl/commit/8aefef1d74a30007b58c6417e7e3ef01563bd1d0#diff-4f34fa1bdbc35f16f0c5e95699d9a980d0146101f1608f372e03114870835e8f).

**Comment by fonsp** [comment]
Fixed by https://github.com/fonsp/Pluto.jl/pull/1797
