### ISSUE TITLE
ProgressLogging progress is not logged anywhere

### ISSUE THREAD

**Issue by sethaxen** [fonsp/Pluto.jl#1434]
On my machine, if I'm using a package that uses ProgressLogging to log progress, Pluto does not display that progress in the browser console, the REPL, or in the notebook; it seems to be inaccessible, whereas in the REPL, I would usually see some nice progress bar.

Is there a way that this can be adjusted within Pluto? The Turing and SciML stacks (among others) extensively use ProgressLogging, and IDEs like VSCode and Juno support displaying such progress logs.

**Comment by sethaxen** [comment]
As I understand it, #343 is proposing Pluto adding progress meters for long-executing cells. Here I'm noting that Pluto is suppressing all existing ProgressLogging logs instead of logging them to the REPL/browser console like other logs.  Perhaps this was done in #498?

A separate issue is that it would be nice if the Pluto UI could display such progress meters.

**Comment by fonsp** [comment]
Output currently looks like this:

![image](https://user-images.githubusercontent.com/6933510/132106268-20986113-7f26-4f6e-a22b-7939b0445027.png)

In the REPL, there is no output by default, unless you also set up a logging display like TerminalLoggers.jl:

![image](https://user-images.githubusercontent.com/6933510/132106332-013ba860-55ac-489b-8275-8e33b2f41737.png)

**Comment by joshualeond** [comment]
I see this issue is now closed due to the awesome new updates to `Pluto.jl` with logging and the `ProgressLogging.jl` functionality. So the behavior we should see now is more like the following in `Pluto.jl`:

![image](https://user-images.githubusercontent.com/3802502/150664413-49b448a1-3d0e-444d-b517-999881c800a1.png)

However, when using `Turing.jl` and the `AbstractMCMC.jl` packages within `Pluto.jl` the progress info still seems to be suppressed for some reason. I do now see the logging messages but the progress bar still isn't working:

![image](https://user-images.githubusercontent.com/3802502/150664471-8df4d487-e330-4068-97e0-9d1510090c24.png)

@sethaxen do you think this is an issue on the `Pluto.jl` side or more on the `Turing.jl` side?
