### ISSUE TITLE
Soss model macro cyclic references

### ISSUE THREAD

**Issue by sethaxen** [fonsp/Pluto.jl#1438]
![Screen-Recording-2021-09-02-at-5](https://user-images.githubusercontent.com/8673634/131878337-a423b8bc-618c-4e3e-8724-8bd0aa54764e.gif)

It's surprising to me that `let ... end` doesn't solve this, since no matter what the macro is, it isn't able to globally set the value of `x`, so why does Pluto get confused here?

This was brought up in #196 and #979, but both of those issues have been closed, and #1032 has been merged since, so I wanted to note that this is still an issue.

**Comment by MichaelHatherly** [comment]
The latest release doesn't include the macro analysis commits https://github.com/fonsp/Pluto.jl/compare/v0.15.1...main. Using `Pluto#main` works fine for your example from what I can tell.

**Comment by MichaelHatherly** [comment]
One unfortunate part of `@model` that it's returning a `Model` object rather than an `Expr` that can be easily analyzed? So putting something like

![image](https://user-images.githubusercontent.com/6144086/131884164-77c97895-8539-449a-b30f-027de3f18556.png)

Won't react to `slider` changing since it's not directly available in the returned `Model` to be analyzed. @Pangoraw I suppose that's not really able to be handled properly right?

**Comment by sethaxen** [comment]
Ah, this is completely fine. I think it would be considered bad form to put a reactive element inside a Soss model like that. A Soss model after being constructed can be conditioned on a value, and that could be controlled by a slider like this:
![Untitled](https://user-images.githubusercontent.com/8673634/131925047-0ad0f15c-5044-4114-a3ff-b7a3aba7d38c.gif)

I can confirm that on main, Soss now works in Pluto. Thanks!
