### ISSUE TITLE
Missing column types in Union{Missing,T}

### ISSUE THREAD

**Issue by juliohm** [fonsp/Pluto.jl#1490]
Screenshot is self-explanatory:

![image](https://user-images.githubusercontent.com/3345261/134523627-fdea207a-3da1-4bef-93de-24128d16dc48.png)

**Comment by disberd** [comment]
Isn't this due to the columns without types containing more than one concrete type? (I see missing in all of them).

I tried randomly with a very short notebook and this also seem to happen for short tables:

![image](https://user-images.githubusercontent.com/12846528/134537732-eb6083cf-b1e9-461e-879e-642c7576f8f8.png)

**Comment by MichaelHatherly** [comment]
Looks to just need an extra dispatch on `trynameof` to deal with `Union{Missing,T}` like `DataFrames` displays it.

![image](https://user-images.githubusercontent.com/6144086/134541041-d8eb5516-5fbe-41c5-b1d7-3d0faa63c005.png)

**Comment by fonsp** [comment]
@MichaelHatherly Will this be your first PR? 🥳🥳🥳

**Comment by MichaelHatherly** [comment]
Yeah, can sort it shortly.
