### ISSUE TITLE
@benchmark not reactive

### ISSUE THREAD

**Issue by aplavin** [fonsp/Pluto.jl#1496]
This is basically a duplicate of https://github.com/fonsp/Pluto.jl/issues/1483, cannot add comments there anymore.
The issue happens with different macros, and `PlutoTest.@test` was just an example - that particular case is indeed fixed now. But others still don't work:
![IMG_0216](https://user-images.githubusercontent.com/687995/134619937-abbf1faa-03ed-4926-9326-064fb997d5b3.jpeg)
Re-evaluating the last cell shows the correct output.

**Comment by dralletje** [comment]
Yeah...

This is a problem with how the @benchmark macro works, there is no way for us to see it depends on `f` :/
The reason for this is the same reason that using local variables in your benchmarks doesn't work:
```julia
let
	x() = 1
	@benchmark x()
end
```
There could be an exception specifically built in for BenchmarkTools, but I don't think we'd want something like that yet.

You can add your own benchmark wrapper that will allow Pluto to see what it depend on:
```julia
macro pluto_benchmark(x)
	quote
		if false
			$(esc(x))
		end
		@benchmark $(x)
	end
end
```

**Comment by Pangoraw** [comment]
Since this is at the boundary of code and data, perhaps we can explore the `Expr(:copyast, QuoteNode(ex))` pattern which I have only seen in macro expansions and assume that this is referencing values that will be used by the code ?

https://github.com/fonsp/Pluto.jl/compare/main...Pangoraw:explore_copyast?expand=1
