### ISSUE TITLE
Is static HTML export broken in 0.16.1?

### ISSUE THREAD

**Issue by neelsmith** [fonsp/Pluto.jl#1529]
In 0.16.1 I'm not seeing content when I do a static HTML export of a notebook.  (PDF and notebook export work fine.)  I was exporting to static HTML in Pluto 0.15.x and I don't *think* I'm doing anything different (?)

Example:   I'm attaching a one-cell notebook.  Here's what I get when I export to static HTML: https://raw.githubusercontent.com/neelsmith/cite-write/main/docs/teeny.html

What am I missing to see this as a webpage/run on mybinder?

[teeny.jl.txt](https://github.com/fonsp/Pluto.jl/files/7267816/teeny.jl.txt)
.

**Comment by neelsmith** [comment]
Possibly related to this conflict with HTTP?
https://discourse.julialang.org/t/pluto-a-conflict-with-http/69039

**Comment by fonsp** [comment]
@ctrekker Export on the main branch is not working because of the CM6 rewrite, but that's unrelated to released versions

**Comment by fonsp** [comment]
@neelsmith It's probably not related to the HTTP conflict, because the static HTML preview is not using a server, but thanks for sending the link!

**Comment by fonsp** [comment]
@neelsmith Looking at your HTML file, it looks like you are using the `main` branch of Pluto, instead of a released version. Like Connor pointed out, HTML export on the `main` is broken, the feature only works when you are using Pluto at a released version.

To go back to the released versions of Pluto:

julia```
pkg> rm Pluto
pkg> add Pluto
```
