### ISSUE TITLE
Dispatch does not work as expected for Base.show inside Pluto

### ISSUE THREAD

**Issue by itsdfish** [fonsp/Pluto.jl#1570]
I encountered an issue with dispatching on vectors using Base.show.  In the MWE below,  I define a method for a custom type and a method for the vector of a custom type.  When calling `[MyStruct(1,2)]`, I expected `Base.show` to dispatch on `M::Vector{MyStruct}`. However, if you paste the code into Pluto,  it dispatches on `M::MyStruct`. By contrast, the REPL dispatches on `M::Vector{MyStruct}` as expected.

This behavior struck me as unusual. Is this expected behavior? 

**MWE**
```
begin
	struct MyStruct
		x
	end
	
	function Base.show(io::IO, ::MIME"text/plain", M::MyStruct)
              Base.show(io, "MyStruct")
	end
	
	function Base.show(io::IO, ::MIME"text/plain", M::Vector{MyStruct})
               Base.show(io, "Vector")
	end
	# show this:
	[MyStruct(1)]
end
```
**Output**

REPL: "Vector"

Pluto: "MyStruct"

**Version**

Julia 1.6.3
Pluto 0.16.1

**Comment by fonsp** [comment]
This is because Pluto uses its own data viewer for `AbstractVector` types, which has precedence over user-defined show methods for a `Vector` type. This works well for most existing packages, but it can be annoying in new packages.

We are working on a way to disable Pluto's viewer for your data types!
