### ISSUE TITLE
vscode integration

### ISSUE THREAD

**Issue by xgdgsc** [fonsp/Pluto.jl#158]
With recent improvements of julia vscode extension (https://github.com/julia-vscode/julia-vscode/pull/1222). Is it possible to integrate this into vscode extension?

**Comment by fonsp** [comment]
A big part of the Pluto experiment is _trying out new UI_ to improve the programmer experience. You can see this today - there are fundamental differences between the experience inside Pluto and that inside a linear code editor, partly to work well with reactivity. And there is still a lot that we want to do! See #116 for example.

Reactivity makes programming easier, and it would be great to see it in more programming environments, but it is far from trivial to do it in a sensible way. (This is why we decided to start from scratch.) Because if the reactivity _breaks_ somewhere, then it suddenly becomes an additional layer of things to worry about, the opposite from what we want.

So... maybe one day!
