### ISSUE TITLE
new cyclic reference error in 0.17

### ISSUE THREAD

**Issue by simeonschaub** [fonsp/Pluto.jl#1616]
The following example worked just fine in 0.16, but seems to have regressed:

```julia
### A Pluto.jl notebook ###
# v0.16.4

using Markdown
using InteractiveUtils

# ╔═╡ aa5a9924-38ee-11ec-0855-99c483114aa2
f(x) = length(x)

# ╔═╡ 02d2a2a6-a806-4263-8368-6bf4eed4bde2
begin
	struct A end
	g(a) = f(a)
	Base.length(::A) = 7
end

# ╔═╡ Cell order:
# ╠═aa5a9924-38ee-11ec-0855-99c483114aa2
# ╠═02d2a2a6-a806-4263-8368-6bf4eed4bde2
```

Pluto 0.17 complaints that there are "Cyclic references among f, A length". While this works if the block is split up, it still seems to me like this shouldn't error since the order functions are defined in doesn't matter until they are actually called.

**Comment by fonsp** [comment]
Hi Simeon!
The change in 0.17 is that we now understand that `Base.length` and `length` are the same. With this new knowledge, Pluto sees the circular references. 

You are right that this instance of circular references should probably be allowed (since both are function definitions), we are tracking that in #178.
