### ISSUE TITLE
Floating-point display precision

### ISSUE THREAD

**Issue by MikaelSlevinsky** [fonsp/Pluto.jl#167]
Float16, Float64, BigFloat.

**Comment by fonsp** [comment]
Can you post a screenshot to show what you mean?

If something unexpected happened, can you also show a screenshot of the Julia REPL doing the same thing?

**Comment by MikaelSlevinsky** [comment]
<img width="491" alt="Screen Shot 2020-06-09 at 1 05 00 PM" src="https://user-images.githubusercontent.com/8176037/84183875-21d70000-aa52-11ea-9474-a843e428bf53.png">
<img width="712" alt="Screen Shot 2020-06-09 at 1 06 29 PM" src="https://user-images.githubusercontent.com/8176037/84183896-24d1f080-aa52-11ea-9917-53479dd811f6.png">

**Comment by fonsp** [comment]
Thanks!

**Comment by fonsp** [comment]
![image](https://user-images.githubusercontent.com/6933510/87250959-a0b3c400-c468-11ea-8b83-ee29b20dec4f.png)

**Comment by nathanieldaw** [comment]
Perhaps relatedly Pluto seems now to differ from the repl (and Jupyter) in using more digits inside arrays of floats. This is awkward because fewer columns fit across the screen.

![image](https://user-images.githubusercontent.com/16307904/92257780-c9be6700-eea3-11ea-8ea1-b259c0bc8620.png)
![image](https://user-images.githubusercontent.com/16307904/92257836-dd69cd80-eea3-11ea-8399-7c7354016e9b.png)

**Comment by fonsp** [comment]
Fixed

![image](https://user-images.githubusercontent.com/6933510/97807981-2f409100-1c64-11eb-8aed-e6e83b9f73c2.png)
