### ISSUE TITLE
Live documentation of CairoMakie consumes 100% CPU

### ISSUE THREAD

**Issue by ForceBru** [fonsp/Pluto.jl#1692]
In Pluto v0.17.1-2 Live docs is really slow. I used to be able to type code with the docs open, and it would be updated on-the-fly. Now I type one character - and it gets stuck using 100% CPU (one full core, that is).

When the binding doesn't exist (say, I'm typing: `C`, `Co`, `Col`, ..., `Colorba`), everything works fine. Once I type that last `r` to get `Colorbar` from Makie.jl, CPU usage spikes, Live docs freezes for several seconds, then everything unfreezes and documentation appears. Same thing happens with any other identifier.

- Pluto v0.17.1-2
- Julia 1.7.0-rc1
- Safari 15.0

**Comment by fonsp** [comment]
Can you make a screen recording demonstrating the problem? Does it also happen for base functions, like `sqrt`?

**Comment by ForceBru** [comment]
![Screencap](https://user-images.githubusercontent.com/8695383/143687010-dcc1d57a-9343-4946-a7c1-60ecd7c254c2.gif)

Base functions seem to work fine, but the whole notebook freezes after I type the `e` to get `CairoMakie`. This looks like a still frame in the recording, but it's not. The notebook becomes unresponsive for quite a few seconds and starts consuming 100% CPU. Same thing with `CairoMakie.Colorbar`. However, as briefly shown in the recording, the docs for `CairoMakie.Color` are shown immediately.

**Comment by karlwessel** [comment]
I noted the same thing happening even without any libraries.

A MWE is to type
```
test() =
```
in a cell, then with the live docs open, repeat the following steps to see a small lag:
1. type a space directly after the equality sign -> a small lag occurs
2. replace the space with a two by:
    1. typing backspace to delete the space and
    2. typing a `2` directly after the equality sign -> no lag
3. replace the two with a space again by:
    1. typing backspace to delete the two and
    2. going back to step 1

You can repeat this as often as you like to see the lag, at least with my rather slow PC. 

When the same steps are repeated with the Live Docs closed there is no lag.

I think the lag gets worse the longer the notebook is or the more libraries are used.

**Comment by karlwessel** [comment]
This was introduced between https://github.com/fonsp/Pluto.jl/commit/e867a5ba13820afaf1cbb7c2a9e4817c2f84c831 and https://github.com/fonsp/Pluto.jl/commit/df7de2ae464ea2080f58146cef97d96ca5fa0f4

![liewview](https://user-images.githubusercontent.com/64231/148674502-f133a3ca-9a43-44ad-9198-db3cc5b992ef.png)

For all commits in between you can't even start a notebook.

**Comment by blepabyte** [comment]
The issue seems to be related to syntax highlighting of code blocks in the live documentation. 
![image](https://user-images.githubusercontent.com/74576829/154880441-d93f23e2-e92e-4985-b00b-63470e7db562.png)

The call to `innerText` on line 507 of `frontend/components/CellOutput.js` seems to trigger a [page reflow](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) which might be what causes the UI to freeze, especially when many packages are loaded and the same function name has many overloads, each with its own code block for docs. Also, the problem seems to be worse on Firefox, but still noticeable in Chrom(e|ium) browsers. 

For testing, commenting that line out and using `doc: ""` instead significantly reduces lag (though breaks docs), and not constructing an `EditorView` at all completely eliminates any lag while typing with the live docs open (still get docs, though without syntax highlighting). 

I don't know how to fix this (not sure if it's possible to store the original text of `code_element` in a property and use that instead of a call to innerText, or run syntax highlighting on the code block directly) but this might help someone else eventually resolve the issue.

**Comment by karlwessel** [comment]
Thank you so much for looking into this!

Can we just disable syntax highlighting as a quick fix? This issue is currently nailing me to Pluto 0.16.1 and I really would love to get rid of the reminder that there is a newer version available :).

**Comment by fonsp** [comment]
@dralletje
