### ISSUE TITLE
`publish_to_js` for `SubString`

### ISSUE THREAD

**Issue by MichaelHatherly** [fonsp/Pluto.jl#1766]
Currently (0.17.3) doesn't allow transparently handling `SubString{String}` for the user and you first have to manually convert to `String` before passing it through:

![image](https://user-images.githubusercontent.com/6144086/146558314-768674a2-ca5c-4ccf-ab32-a6a313eb6069.png)

Is this something that's relatively simple to support?

**Comment by fonsp** [comment]
We could add conversions (like automatically `collect`ing an `AbstractVector`), but it will take some effort because we don't want to mutate the given object, and we don't want to cause allocations if we can avoid it.

I think it might not be worth the trouble, because this API is quite low-level, most users won't use it directly?

**Comment by dralletje** [comment]
`convert()`? But indeed I tend to requiring the `convert` call on the caller side.

**Comment by fonsp** [comment]
Supporting AbstractString is not too hard because we can convert, but then we also want to support `[1, a_substring]` and such
