### ISSUE TITLE
MathJax not rendered in exported static HTML

### ISSUE THREAD

**Issue by mdAshford** [fonsp/Pluto.jl#1987]
<img width="980" alt="simpleMJX jl-staticHTMLexport" src="https://user-images.githubusercontent.com/42947897/158494047-48e0de35-039f-4e6a-ac56-a4bf9e307243.png">

MathJax is not rendered in exported Static HTML.

This gist contains the Pluto notebook and its static html export.
https://gist.github.com/mdAshford/2a7debbe3b022b88146cdc7d150cfa8f

I'm running Pluto.jl v0.18.2

The offending code in the exported html appears to be in the script tag where MathJax is loaded. (line 56 in the gist). 
Changing `not-the-src-yet="https://cdn...` to `src="https://cdn...` solves the problem.

```html
<!-- This script will be enabled by JS after the notebook has initialized to prevent taking up bandwidth during the initial load. -->
<script type="text/javascript" id="MathJax-script" not-the-src-yet="https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/tex-svg-full.js" async></script>
```

Thanks for a great platform!

**Comment by Pangoraw** [comment]
@fonsp I don't really know how to test locally but the issue is that the setup_mathjax is not called for static exports anymore because there is only one component render. A possible fix is calling setup_mathjax in the constructor for static previews: https://github.com/fonsp/Pluto.jl/commit/251af10d1a1d686ad3f4118abd1a58a8b561a7be

**Comment by likanzhan** [comment]
Same issue being encountered.

**Comment by rgouveiamendes** [comment]
I think this problem came back. You can check it here: https://rgouveiamendes.org/teaching/iscte-iul/econometrics-i/notebooks/Capitulo01
![Screenshot 2024-02-06 125429](https://github.com/fonsp/Pluto.jl/assets/29065018/55bedb36-9c51-439c-9587-5adb3d51ba98)

The browser tells me the following:
![Screenshot 2024-02-06 201120](https://github.com/fonsp/Pluto.jl/assets/29065018/7d5699b7-814e-46c2-b9cb-861873f23e59)

**Comment by fonsp** [comment]
It seems to work on my computer! Did you update the notebook since you posted your comment?

**Comment by rgouveiamendes** [comment]
To make it totally clear: the problem is with the **static HTML version of the Notebook**. The active version renders the math perfectly. This thread in discourse https://discourse.julialang.org/t/math-not-displaying-properly-in-static-html-pluto-notebook/109790/4 has a user with a Mac experiencing the same problem. It seems that using `PlutoPlotly.jl` fixes the problem because, as far as I understand (which is not very far...), it forces Matjax to run locally.

**Comment by fonsp** [comment]
Thanks! @rgouveiamendes in the future, be sure to crosslink when you make the same post in two places, otherwise you might cause the community to spend double work to help you. I will close this thread
