### ISSUE TITLE
Revise functionality got lost

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#2094]
Hi, Revise ceased to work with Pluto. I did some bisection, and it seems it happened between 0.18.0 and 0.18.1

The context is a project with a locally used subpackage. I can setup a git repo if you like to have an MWE for this.

**Comment by rikhuijzer** [comment]
> Hi, Revise ceased to work with Pluto. I did some bisection, and it seems it happened between 0.18.0 and 0.18.1
> 
> The context is a project with a locally used subpackage. I can setup a git repo if you like to have an MWE for this.

Worked for me this afternoon still on the newest Pluto version

**Comment by fonsp** [comment]
Thanks for the bisection! Here is the diff: https://github.com/fonsp/Pluto.jl/compare/v0.18.0-src...v0.18.1-src 

Looking through the commits, nothing obvious stands out. There was only one significant backend change, https://github.com/fonsp/Pluto.jl/commit/7a74c63e887772d543b336d3540ddf588aa76965, but this was only a refactor of cell ordering logic. There is a small chance that this caused `using Revise` to run after `using MyPackage` instead of before, if the two imports are in different cells. If so, can you do `using Revise, MyPackage` to force Revise to load first?

Perhaps the subpackage is the problem? Does Revise work if you import directly?

**Comment by j-fu** [comment]
... this must have been a confluence of bad circumstances on my computer I cannot reconstruct anymore  It seems now working well. So I close this.
