### ISSUE TITLE
[Feature Request] Double click to edit cell

### ISSUE THREAD

**Issue by briochemc** [fonsp/Pluto.jl#210]
It would be very nice if double-clicking a cell unfolded its code for editing (as is done by Jupyter). No idea how hard it is to implement, but this would reduce the number of clicks and improve productivity when creating content IMHO.

**Comment by fonsp** [comment]
Suggestions are hard to answer objectively, so here are some wavy thoughts:

Clicking cell output used to be the way to fold/unfold a cell (before `0.5`?), but after adding `@bind` I moved it to a separate button because:

1. Two unrelated actions had the same input method: interacting with bound variable and unfolding code. In the case of double click, there is still a number of actions that would accidentally trigger folding: e.g. double clicking to select, or double clicking the same button.

2. The notebook felt _fragile_, because clicking somewhere on the page would change it. Pluto notebooks are also _documents_, and online documents normally don't change when you double click.



Double clicking the cell shoulder (the thing left of a cell) could work, although this is also mixing up UI concepts: the click shoulder would be both a click handler and a drag handler. (Although you see that more often in UI)

**Comment by briochemc** [comment]
Thanks for your reply! To me, your point about double-clicking a button is the strongest one. What about triggering the unfold-action only when clicking a cell *away from its interactive bindings*. E.g., assume you have a cell with a slider, a button, and a text-box to write in. Double-clicking any of these elements uses the current behavior. But double-clicking somewhere else in the cell unfolds the code for you to edit it. 

This does not solve the [double-click to select] issue, but I think that's OK because once unfolded, then you can double-click that text again inside the unfolded code.

And it does make the notebook "*feel fragile*", but I guess I would be OK to trade this fragility for more productivity!

**Comment by fonsp** [comment]
What are your thoughts about double clicking the cell shoulder?

**Comment by briochemc** [comment]
> What are your thoughts about double clicking the cell shoulder?

To be honest, I don't know... I guess I'd have to try it to see how it feels? But my (uneducated) intuition is that most Pluto users will come with a mostly-Jupyter experience, and expect their muscle-memory to work in both systems?

**Comment by fonsp** [comment]
Jupyter has double clicking the cell shoulder to fold/unfold cell output, so it is actually quite close.

It sounds like the underlying issue here is that it takes too long to toggle folding a cell. Other solutions are a keyboard shortcut and making the click area of the 👁 button larger.

**Comment by fonsp** [comment]
I have moved this to the [suggestion box](https://github.com/fonsp/Pluto.jl/issues/182#issuecomment-643252439) 🐹
