### ISSUE TITLE
[Help] ArgumentError: Package Distributions not found in current path

### ISSUE THREAD

**Issue by hungpham3112** [fonsp/Pluto.jl#2202]
I have downloaded all required packages and tried to use those in notebook but it raises error:

```
ArgumentError: Package Distributions not found in current path:

- Run `import Pkg; Pkg.add("Distributions")` to install the Distributions package.
```

Here is video for details:

https://user-images.githubusercontent.com/75968004/177242529-cfca5751-16e0-40ac-a0f2-08549f956dd2.mp4

Pluto requires restart the notebook so many times. I don't understand that. Thanks in advance for helping me

**Comment by Pangoraw** [comment]
Are there any log message in the terminal where Pluto is running ? could you also share your notebook file?

**Comment by rikhuijzer** [comment]
> I have downloaded all required packages

I would highly recommend to remove your globally installed packages except for a few such as Pluto and Revise. In Julia, it's much better to only install the packages you need in a separate environment. Pluto can manage these environments automatically for you. The benefit is that installing everything globally will cause you to get stuck on old versions since any package can block other packages from updating.

**Comment by hungpham3112** [comment]
I think I should close this question in here.
