### ISSUE TITLE
DataFrames.jl+Pluto.jl integration

### ISSUE THREAD

**Issue by bkamins** [fonsp/Pluto.jl#2206]
In https://github.com/JuliaData/DataFrames.jl/pull/3096#issuecomment-1175284117 there is a question on DataFrames.jl+Pluto.jl integration.

The issue is:

> Pluto.jl does some customization if the `class` in `div` and `table` is `data-frame`. Some of those customization overrides what we selected in [DataFrames.jl]

The question is should we go forward with it (i.e. let Pluto.jl override the settings of DataFrames.jl or this should be somehow synchronized).

On DataFrames.jl side the issue is triggered by the fact that we want to switch to PrettyTables.jl for HTML rendering.

**Comment by lungben** [comment]
I think it would be really cool to have an interactive table display in Pluto for DataFrames as default, with searching, filtering, sorting and pagination.

Some time ago I did some experiments with agGrid (https://github.com/lungben/PlutoGrid.jl ), what looks quite promising.
One issue there is how to deal with large DataFrames - for sorting, filtering, pagination, etc. agGrid needs to have the whole DataFrame in the frontend. Maybe load only a specific amount of data into the table viewer (e.g. 10k lines) and add a button to load more/all data?

**Comment by bkamins** [comment]
VSCode had the same issue (also TerminalPager.jl) - the only solution is paging loading of data frame data into cache AFAICT.

**Comment by bkamins** [comment]
@fonsp - when you look at this issue can you please coordinate with @ronisbr (all these changes are related to PrettyTables.jl 2.0 release that is going to happen soon).

**Comment by bkamins** [comment]
x-ref https://github.com/JuliaData/DataFrames.jl/pull/3096#issuecomment-1241960879 (just to keep track all comments in one place)

**Comment by fonsp** [comment]
It looks like the PR is fine from Pluto's perspective because, like you mentioned, Pluto does not call the default HTML show method unless you explicitly ask it to (using something like AsMIME.jl). About the CSS styles: all our custom styling is [scoped](https://github.com/fonsp/Pluto.jl/blob/5c24f42c56535c6c8a6b74538037a14c666b5685/frontend/treeview.css#L274-L340) to our custom viewers only, so it will not interfere with PrettyTables.jl.

We designed a custom table viewer because we wanted to improve the default in DataFrames.jl, and because we want to support lazy loading more rows and columns. Lazy loading is still very important, so we will keep our custom viewer for now, but I would be interested to look at the improvements in PrettyTables.jl and bring some of them to Pluto!

**Comment by fonsp** [comment]
I understand that it is frustrating right now that all the cool work into PrettyTables.jl and DataFrames.jl will not be visible to Pluto users, but let's try to get some of the nice new features into Pluto soon!

**Comment by bkamins** [comment]
It is fine from DataFrames.jl perspective.
