### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by malyvsen** [fonsp/Pluto.jl#23]

**Comment by malyvsen** [comment]
I'm making icons right now, here's a preview: 
![image](https://user-images.githubusercontent.com/5940672/75681702-6ead7c80-5c94-11ea-8b5c-75695c0ac5b6.png)

**Comment by fonsp** [comment]
For new collaborators - we also have a mood board on google docs! Let us know if you would like to see 👀

**Comment by fonsp** [comment]
#2

**Comment by fonsp** [comment]
The `.css` structure should be simpler - no `<style>` tags inside `editor.html`

**Comment by fonsp** [comment]
Perhaps `PLUTOCONFIG` can be used to send the .css file to the client? But this would give a 'flash of unstyled content'.

Or a simple substitution thing could be made for `.jlhtml` files: make it so that you can write `$(string_interpolation)` inside the HTML document, like:
```
<style src="$(path_to_css)">
```

This is needed anyways to do #77 

 Maybe check performance first?

**Comment by fonsp** [comment]
Maybe it would be good to first check whether Plots.jl (or whatever backend) can be persuaded to work in a dark mode? Otherwise your plots would look pretty bad

**Comment by malyvsen** [comment]
I think people would need to use [PlotThemes.jl](https://github.com/JuliaPlots/PlotThemes.jl) for this.
But even if there were a way to make Plots.jl work in dark mode, I don't think we should do it for the user? It would be invisible messing with someone's code.

**Comment by fonsp** [comment]
Ah okay, I agree 👍

**Comment by fonsp** [comment]
As discussed in #2, a dark mode can [automatically match the system theme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), we don't necessarily need our own config for this. 

I would say that the printed document is always in light mode?

**Comment by fonsp** [comment]
To new contributors: the plan is to rewrite `editor.css` to use more CSS variables defining a color scheme, font, etc. Then there would be a short CSS defining the color scheme (which can be swapped out for a 'dark mode CSS') and a longer CSS close to what it is today.

This makes it _easier to maintain the package_ because we will only have one CSS file to worry about.

**Comment by fonsp** [comment]
And check whether all the sample notebooks still look nice

**Comment by shahid777-py** [comment]
Guys, im new to julia and i love Pluto.jl but is there any way to get dark mode, or did you merge the patch.

**Comment by dralletje** [comment]
https://github.com/Pocket-titan/DarkMode

**Comment by MarkNahabedian** [comment]
This is an accessability issue for me.  Most of the Pluto user interface (hiding cells, and adding new cells are the only buttons I've found so far -- through painstaking examination of the DOM tree) is invisible if one's browser is in dark mode.

**Comment by pbignardi** [comment]
Currently working on this, and managed to separate all the color variables in a separate file. 😃  Though, some design decision are to be made about the way to select dark and light mode and the possibility to include other different themes (might as well since the code would support it). Any inputs? Thanks 😉

**Comment by MarkNahabedian** [comment]
Ideally it would query the browser to get the user's preferred theme.  I think I'm stating the obvious though.

**Comment by dralletje** [comment]
@MarkNahabedian what do you mean with invisible if your browser is in dark mode? You're using an extension? Because by default dark mode doesn't change any styles for websites..

@pbignardi taking the user preferred color scheme would be ideal, I'm not too fond about having user specified themes integrated into Pluto.

**Comment by MarkNahabedian** [comment]
I mostly use Chrome.  I think I installed an extension there before Chrome respected the system theme.

I seldom use Edge and have not extended it.  It respects the system's dark theme.  Pluto's buttons are just as invisible there.

**Comment by dralletje** [comment]
You happen to have a screenshot?

**Comment by MarkNahabedian** [comment]
I'm on a Microsoft Surface.  <Windows key><volume down> is supposed to take a screenshot but doesn't.

I tried Microsoft Edge's "web capture" menu item and selected full screen capture.  It did something but I don't know where it put the screenshot.  It resulted in all of Pluto's non-cell background changing from black to white, and the icons becoming barely visible if I look real close, but the contrast is really poor.  If I reload the page the black background is restored.

I took a photo which is shared here:
https://photos.app.goo.gl/AWURjmDozT99Qp759

Because of the heated competition to give us smart phones with cameras that give us a couple of orders of magnitude more pixels than we need, the image was too big to email.  Sorry about the glare.

I meant to say this before: much thanks to those who are working on this issue.  The very nature of vision limitations makes the so afflicted more likely to use computers than to play baseball.

**Comment by dralletje** [comment]
Thanks for the photo, that makes stuff a bit more clear.
You happen to have "Force Dark Mode for Web Contents" on? (As describes in under "How to Force a Dark Theme on All Websites
" in [this article](https://www.howtogeek.com/360357/how-to-enable-dark-mode-in-microsoft-edge/))

I hope introducing our own dark mode disables the force dark mode so you can see the buttons again 😁

**Comment by MarkNahabedian** [comment]
What I see doesn'y quite match that description.

In Edge settings, under Appearance, I have "overall appeaqrance" set to "dark" and "theme" set to "defailt".

**Comment by pbignardi** [comment]
I'm changing all the colours for all the elements in the DOM and I just found a little problem. Caret color cannot be set in any way through CSS for the pluto-input. Any inputs?

Also, the colours for highlighting the syntax in the input are fixed in the ```CellInput.js``` file; should the dark mode have different highlighting colors to allow for better readability? If so, how could we takle the problem without messing too much with the javascript part?

**Comment by dralletje** [comment]
It should definitely have different highlighting: we can add some javascript that pulls the colors from the computed css.

**Comment by pbignardi** [comment]
Code highlighting has been fixed. Though selecting code and cursor Color are buggy. Somehow, somewhere, the JavaScript code for CodeMirror chooses its own colors. 

Those two problems aside, the dark mode is complete. 

If anyone has suggestions to solve the two mentioned problems I'll be very grateful
