### ISSUE TITLE
Run cell button not visible

### ISSUE THREAD

**Issue by VivaldoMendes** [fonsp/Pluto.jl#2313]
In Pluto v0.19.13, Julia 1.8.2,  on a windows machine, the `Run cell` button is not visible. It used to be visible in previous versions.

**Comment by fonsp** [comment]
@VivaldoMendes can you make a video recording of the problem?

**Comment by VivaldoMendes** [comment]
Hi @disberd and @fonsp,

Sorry for my late reply; I had a busy day. Moreover, I needed to check the problem on different computers to avoid throwing more noise into the problem rather than helping.

I do not understand what is happening, but the problem is simple to explain. We do not need a video, but I will post one if that is the case.

I tested the problem on various Windows computers, some with Julia 1.8.1, others with Julia 1.8.2, all with the latest version of Pluto v0.19.13. The problem is simple: the `Run cell` button is not visible; it works if we click on its usual place, and the output is obtained as usual. The only problem is that the small round button is not visible. That is all.

I just started a new notebook to make things as simple as possible. Typed `3*3`, run the cell, the output is visible, but the run-cell button is seen nowhere. See the figure below.


![a2](https://user-images.githubusercontent.com/48516539/195722780-1c9dc735-0476-4f67-b0a9-bac39a48e155.png)

My configuration can be seen below.

![a1](https://user-images.githubusercontent.com/48516539/195722827-17d43e03-8819-4d54-9ecb-1523baa4229d.png)

Thanks.

**Comment by fonsp** [comment]
Hard to tell without a video (@VivaldoMendes could you try to make a video? Instructions are [here](https://github.com/fonsp/Pluto.jl/issues/new?assignees=&labels=&template=bug_report.md&title=)) but it it possible that OP uses a touch-enabled screen, for which we have some different CSS rules.

**Comment by disberd** [comment]
I also noticed this now randomly while testing a connection to a remote pluto server through a local browser instance.
For some reason my local pluto server still uses url for svg background images instead of the one directly bundled with Pluto (I thought this only happened if I dev Pluto).
On the server one, I see a bunch of bundled images but the specific one of the run button seems to be broken.

All the others svg can be seen both in the front-end and in the _Sources_ tab in the developer console.
The `caret-forward-circle-outline.svg` seems instead broken, showing just this if I try to open the bundled image in a separate tab:
![image](https://user-images.githubusercontent.com/12846528/195843359-6a3e8c6d-07f9-44e4-8942-38f6f6262b41.png)

**Comment by fonsp** [comment]
It looks like the file in our bundle is empty: https://github.com/fonsp/Pluto.jl/blob/v0.19.13/frontend-dist/caret-forward-circle-outline.38d394c2.svg

Which is very weird, we check for this situation explicitly:
https://github.com/fonsp/Pluto.jl/blob/33b506b359cd41adb56bb9496d18062bc00486f1/frontend-bundler/parcel-resolver-like-a-browser/https-resolver.js#L93-L103
