### ISSUE TITLE
Issue with colored image plotting

### ISSUE THREAD

**Issue by tknopp** [fonsp/Pluto.jl#2330]
Hi, 

when plotting a colored matrix, `Plots.jl` recognizes that this is an image and renders it upside down with square pixels. This used to work in Pluto as well.

What now happens is that the coordinate system is wider than the actual image size. In a previous version (last year) of Pluto this was not the case and the axes was tight. Also when I use Plots.jl on the REPL, the axes are tight.

<img width="825" alt="image" src="https://user-images.githubusercontent.com/3109172/196777644-4e737cbe-16e3-464e-a81d-32ab17ac14c7.png">

If this is not a bug, is there some way to enforce the axis fitting to the image?

Thanks,

Tobi

Here is the Pluto notebook to reproduce the issue:

https://gist.github.com/tknopp/aa91e96df9b7949db723eb9616828674

**Comment by fonsp** [comment]
Hey @tknopp ! I suspect that this is a change in Plots.jl since last year.

Did you know that you can use `ImageShow` for this purpose? You also need to import `ImageIO`:

<img width="655" alt="Scherm­afbeelding 2022-11-15 om 12 40 17" src="https://user-images.githubusercontent.com/6933510/201910835-3caeb9f1-bfff-43fe-930d-bd5e0dc2e697.png">
