### ISSUE TITLE
Pluto has hidden state and a mutable workspace in plots

### ISSUE THREAD

**Issue by najtin** [fonsp/Pluto.jl#2344]
1. 📹 A video recording demonstrating the problem. (You can drag a video file into this box)
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/42641080/198037143-bae7fff4-3272-480a-9cfb-8b31ee59533c.gif)

2. 📝 A short Pluto notebook file. (Upload the notebook file to https://gist.github.com/ and include the link.)
https://gist.github.com/najtin/2ee0e788dffd86f32c53a619ed5964cb

3. 🤕 Try to clearly explain what the problem is, it might not be obvious to others! Instead of saying: "This does not work.", try to say: "I expected ..., but instead I am seeing ..."

In the readme of this repository it states:
> Pluto offers an environment where changed code takes effect instantly and where deleted code leaves no trace. Unlike Jupyter or Matlab, there is no mutable workspace, but rather, an important guarantee:
>
> >    At any instant, the program state is completely described by the code you see.
>
> No hidden state, no hidden bugs. 

Therefore i expected that the order in which i run the cell wouldn't effect the output of the notebook. Maybe there is a misunderstanding somewhere on my side. What is happening is that the order in which i run the cell does effect the output of the notebook. 

You can even delete the histogram cell after you ran it with shift+enter, and than run the plot! cell. Thus, Pluto does offers an environment where deleted code leaves traces, and that it has indeed a mutable workspace like Jupyter and Matlab.

Thanks for your time!

**Comment by fonsp** [comment]
Thanks for the issue @najtin !

In this case, a design goal of Pluto (no hidden state) cannot align with a design goal of Plots.jl (a "current plot" concept with modifier functions like `plot!`). 

These misalignments happen sometimes, because we would like to support all packages, even if they are designed for an imperative programming style. We have some discussion about how to improve this experience here: #316 and #564
