### ISSUE TITLE
For-Loops penalty

### ISSUE THREAD

**Issue by natgeo-wong** [fonsp/Pluto.jl#2348]
There seems to be a penalty for for-loops in Pluto.jl notebooks that does not exist when julia scripts are run in the terminal.

For example, the code chunk
```
bin_frq[:,:,:,mo] += tmpdata
```
Takes 2 seconds to run, but the code chunk
```
for ibin = 1 : 100, ilat = 1 : 241, ilon = 1 : 1441
    bin_frq[ilon,ilat,ibin,mo] += tmpdata[ilon,ilat,ibin]
end
```
Takes 50 seconds to run.

**Comment by fonsp** [comment]
Can you give a small notebook file that we can run?

**Comment by abraemer** [comment]
This slowdown is due to repeated access to a global, untyped variable which [the manual warns about](https://docs.julialang.org/en/v1/manual/performance-tips/#Avoid-untyped-global-variables).

[Here](https://gist.github.com/abraemer/d4d0249c76e2eeab138c01eb31490781) is notebook showcasing this effect (using current Julia 1.8.5 and Pluto 0.19.21). The screenshots below are from that notebook for convenience.

![image](https://user-images.githubusercontent.com/11058200/215099146-6caa22ad-526b-4324-94cc-204f70d9e769.png)

Simply putting the stuff into functions to avoid the repeated access to global vars removes the slowdown (and in fact makes the explicit loop faster than the assignment due to less overhead):

![image](https://user-images.githubusercontent.com/11058200/215099434-2d9eb903-e6e2-4977-bb32-c903e09ce224.png)

So Pluto is not to blame for this behavior. But here is a thought: Making the global variables `const` gives the same speedup (since some Julia version I don't remember). Could Pluto make all global varibale constant implicitely? Assignment to a variable is only permitted from a single site anyways, so marking the varibale `const` should not change Pluto's behavior, right?

![image](https://user-images.githubusercontent.com/11058200/215100467-a76aca91-a0d9-49ba-94f4-0a2a69ad031e.png)
