### ISSUE TITLE
print() and @show for intermediate results

### ISSUE THREAD

**Issue by SubhadityaMukherjee** [fonsp/Pluto.jl#245]
For some reason, outputs do not display when it comes to loops. 
Say I have this code. I followed the instructions are removed @info but it only prints to console and not here. Is there a workaround or am I doing something wrong? Since this is a local variable I cant even bind it to display elsewhere...

```julia
#Package used "OpenAIGym"
begin
	global s
	for i ∈ 1:20
	  T = 0
	  R = run_episode(env, RandomPolicy()) do (s, a, r, s′)
	    #render(env)
	    T += 1
	  end
		R2 = R
	  "Episode $i finished after $T steps. Total reward: $R" #Need this to display here 
	end
	close(env)
end
```

On the other hand something like this works.
```julia
begin 
	temp = "123"
	temp
end
```

PS. I love this package. :heart:

**Comment by fonsp** [comment]
Hi Subhaditya,

Thanks for the feedback! Cell output in Pluto is very minimal: 
one cell contains one expression that gives one result. This result is displayed in the notebook.

A begin block shows its output because the `begin` block _returns its last contained value_

So:
```julia
123 == begin
    456
    123
end
```
is `true`. The same goes for the `if`, `let` and `try` blocks. (Try it!)

The `for` and `while` blocks do **not** return anything. (Well... they return `nothing`.) The argument is: the block runs multiple times, so which of those should it return?

# Examples

Say that we have
```julia
for i in 1:20
    R = i+100
    T = R^2
    md"hello $R and $T"
end
```
then this will not return anything -> it will not display anything.

If you want to get something from the final iteration:
```julia
let
    x =  nothing
    for i in 1:20
        R = i+100
        T = R^2
        # something
        x = md"hello $R and $T"
    end
    x
end
```

If you want to see all outputs:
```julia
map(1:20) do i
    R = i+100
    T = R^2
    md"hello $R and $T"
end
```
this will show you the 20-element array, you can click on it to see the intermediate values.

# To print intermediate progress
This is not yet supported inside Pluto, but [there is a plan](https://www.notion.so/print-is-dead-all-hail-the-new-print-24e1c517c3f64bbbbcb97499e2539611).

What you can do is `print(...)` or `@show ` inside your for loop, and look at the _terminal where you launched Pluto_ to check the output.

**Comment by SubhadityaMukherjee** [comment]
Oh okay that is great then! Thank you for the detailed breakdown :)
Do I close the issue?

**Comment by fonsp** [comment]
I'd like to leave it open to remind myself to add this to the FAQ :)

**Comment by SubhadityaMukherjee** [comment]
Okay :+1: 
There. Reopened it. Sorry about that

**Comment by fonsp** [comment]
No worries!

Let me know if you have more questions! Sometimes it's hard for me to see which things are clear and which aren't.

**Comment by ilyagr** [comment]
If you want to discourage people from using `print` in their notebooks, one option that seems nice to me is if `stdout` and `stderr` was redirected to a console presented similarly to the Live docs screen, sort of like the browser's JS console. You don't have to save this output with the notebook.

Some way to see the Julia console output in the browser seems important, especially so for users who are using Binder, or some other installation that doesn't show the console Pluto started from. 

Some things that are nice to be able to see:

- How is the execution of `Pkg.add` is doing? Did it fail? Is everything frozen because the package is compiling? Did the compilation fail terribly and kill the Julia process?

- Same for importing a package.

- `@warn` output. 

- Debugging by putting `@show` in various places.

**Comment by SubhadityaMukherjee** [comment]
@ilyagr Yeah that would be nice.
The issue is that these kind of outputs are essential while training a machine learning model but not so for other code I guess. 
I do have a terminal open and I can view it though so thats not an issue but anyway.

**Comment by evadknarf** [comment]
and to sumplement, how to completely supress any output (such that the cell appears to be a blank line after execution). I call a GC() seems to do the trick but not very nice.

better still if the line itself can be collapsed...

**Comment by fonsp** [comment]
> 
> 
> and to sumplement, how to completely supress any output

add a semicolon `;` at the end of your code.

**Comment by fonsp** [comment]
@ilyagr Thanks for the summary! These are important reasons to include some form of a terminal in Pluto. I like your suggestion:
> it can be closed by default, but have an indicator turn red if anything is printed to stderr (as opposed to stdout), so that the user knows there might be something important to see there.

**Comment by fonsp** [comment]
Also see the zulip thread about this subject here: https://julialang.zulipchat.com/#narrow/stream/243342-pluto.2Ejl/topic/Show.20messages.20in.20notebook.3F
a copy paste of the messages is here: https://gist.github.com/fonsp/d93cb6cea5ab70bdf5cd67ed033a11e4

**Comment by evadknarf** [comment]
> > and to sumplement, how to completely supress any output
> 
> add a semicolon `;` at the end of your code.
> 
> `GC` is unrelated to displaying output, you shouldn't have to use it yourself. The reason that it suppresses output is that `GC()` returns `nothing`, which displays as an empty line in Pluto and the REPL. So adding `GC()` is equivalent to just adding `nothing` at the end of a cell.



> add a semicolon `;` at the end of your code.

my last line is a map function returning array of dataframes. adding a semicolon doesn't supporess the long output...so how else can I achieve it?

**Comment by fonsp** [comment]
```julia
map(x) do y
    z
end;
```

**Comment by evadknarf** [comment]
I rewrote my last line and it doesn't suppress the output: 
![image](https://user-images.githubusercontent.com/14981695/90201589-e53ad280-de0d-11ea-9413-46d99f23236e.png)

**Comment by karlwessel** [comment]
I'm not sure if that behaviour should be considered a bug but: You need to put the semicolon as very last character in the cell, so after the last end.

**Comment by fredrikekre** [comment]
One idea might be to have a (collapsed by default?) inline "terminal" that displays `stdout` and `stderr`.

**Comment by fonsp** [comment]
Yeah that will probably be implemented, although I hope to do something nicer:
https://www.notion.so/a-cooler-way-to-print-24e1c517c3f64bbbbcb97499e2539611

**Comment by c42f** [comment]
Haha I just saw the original title of "a cooler way to print" in the URL you posted (https://github.com/fonsp/Pluto.jl/issues/245#issuecomment-667712678). The parallel with the first example in the [Logging stdlib docs](https://docs.julialang.org/en/v1/stdlib/Logging/#Logging) is pretty striking :laughing:.

More seriously - maybe we could have an extension module which pirates a selection of the `Base` functions which currently have `stdout` as a default first parameter?

For example, `dump` was mentioned on Zulip, and `@capture_out` was suggested as a solution. But internally `@capture_out` is a super heavy weight tool for this. If we pirated `dump(x)` to mean `Text(sprint(dump, x))` casual users might be in a better situation? (Even better, have `dump(x) = Dumped(x)`, and define `show(::IO, mime, ::Dumped)` for appropriate `mime` so we can expose rich object structure in the UI.)

Granted, this is a hack but it might be better than every new user reaching for `@capture_out`.

**Comment by fonsp** [comment]
I agree 100%!

**Comment by z-m-k** [comment]
I understand that one can have a vision of how a perfect notebook system should work (e.g., one cell one statement; as limiting as it is), but this goes too far and makes it hard to recommend Pluto over Jupyter to anyone for me. An ability to print intermediate results within a function is a must-have.

**Comment by c42f** [comment]
> An ability to print intermediate results within a function is a must-have.

If you read the thread you'll see that we agree on this, and are discussing how to do it in a convenient and consistent way.

**Comment by fonsp** [comment]
Sneak peek

![Schermopname 2020-12-30 om 10 34 30](https://user-images.githubusercontent.com/6933510/103342842-d25a2f00-4a8a-11eb-8d5c-1b3fda093874.gif)

**Comment by z-m-k** [comment]
This looks interesting, but I still do not see why you cannot simply respect `println` even if you don't like it. 

What do these dots do? Do I hover over them? Why is it interesting to me to see just the timing of the message rather than the content? Having an indication that there is output in the terminal is quite frankly not that interesting for me as most of the time I run things remotely and do not see the terminal.

The last point is also a no go for me for using this in the classroom as I cannot assume that students have enough compute power to solve all programming assignments or that they can install everything without issues. So this needs to work in the cloud.

**Comment by fonsp** [comment]
Yes you can click/hover to see the message.

_Remember to stay positive when writing feedback to open source projects!_

**Comment by z-m-k** [comment]
You are incorrectly assuming a sentiment in my comments. I am positive about the project and I want to use it, but I also have lots of experience in teaching large courses to "diverse" groups of students. I also want this to work beyond simple code. I am simply providing you with my perspective.

It would still be better to be able to immediately see printouts (even if only the last) as they happen rather than hover/click. Better ergonomics.

A typical use case for this would be to have a function that runs potentially few minutes/hours and prints tens/hundreds of outputs. How are the dots scaled then?

**Comment by RaulDurand** [comment]
> One idea might be to have a (collapsed by default?) inline "terminal" that displays `stdout` and `stderr`.

That is interesting! 
Also, @c42f , what about a small button for each cell that when pressed displays/hides the cell messages in an additional box (as the one for the cell's output value). That box would be collapsed (or inexistent) by default unless there are actual messages.

**Comment by bvdmitri** [comment]
Just a little bit of a feedback of using Pluto over past weekends.

It would be great to have an ability to print something inside Pluto notebooks. I really like features of Pluto, especially live docs and ability to redefine structures, but it is really hard to use it with other libraries which mostly print into stdout. For example I cannot use `@btime` to benchmark my code. Even Julia's `Base` prints sometimes, e.g. `@code_llvm`. 

Just imagine, the first thing programmer does in a new environment/programming language is `println("Hello, world!")`. Pluto notebook silently prints it in a terminal and doesn't display anything in a notebook itself, which is unobvious behaviour. From programming point of view I understand, of course, that `println` returns `nothing` so there is nothing to display, but for new users of your notebook environment it may be very confusing and makes them google for a half an hour just to realise that this is an intended behaviour.

Using `with_terminal` from `PlutoUI` is not an option, because it doesn't allow to return anything from its local scope. Looking in a terminal output is really annoying, distracting and does not work in cases where Pluto notebooks running on a server. Running Jupyter notebooks on a server is very common practice, especially when you work with datasets of hundreds and thousands of GBs. Using `@show`, `@error` and `@warn` with custom logging object won't work for already existing libraries which just use `println` inside them. 

As @z-m-k already mentioned dots are not scaling well for large outputs and counterproductive. Most of the time I'm not interested in positioning or colouring of my output, but in its content. Clicking/hovering over dots is a huge overkill. 

In my opinion, the most convenient and consistent way is to somehow redirect and print **everything** collapsed/expanded above/under the cell as Jupyter notebook does.  I'm not sure what is the main problem of just redirecting all output to the cells as Jupyter notebook does. I suspect it has to do something with the fact that `println` in Julia is asynchronous and moreover it is a side-effect (IMHO, should be considered as a _safe_ side-effect). 

Besides that, Pluto is an amazing project. Well done guys! I hope it will become even better in the near future.

**Comment by cortner** [comment]
could there be a setting that allows you to choose where to direct the output?

**Comment by RaulDurand** [comment]
Meanwhile, I wrote a macro that helps me print intermediate results

```julia
macro seeprints(expr)
	quote
		stdout_bk = stdout
		rd, wr = redirect_stdout()
		$expr
		redirect_stdout(stdout_bk)
		close(wr)
		read(rd, String) |> Text
	end
end
```

and I use as
```julia
@seeprints for i=1:3
	println("Hello ", i)
end
```

**Comment by bvdmitri** [comment]
@RaulDurand wow, interesting solution and works like a charm. Here I use slightly modified version of your code:
```
macro with_stdout(expr)
	return quote
		stdout_bk = stdout
		rd, wr = redirect_stdout()
		result = ($expr)
		redirect_stdout(stdout_bk)
		close(wr)
		print_result = read(rd, String) |> Text
		(result, print_result)
	end
end
```
it allows you to have both printing and result of the expression, e.g:
```
result, _ = @with_stdout f(1)
```

**Comment by Roger-luo** [comment]
I ran into this as well, I need to do a tutorial on Julia, and I just need to show my student what is `@code_warntype`, but the printing is inside the terminal, this is very inconvenient and inconsistent when I do the tutorial online (imagine you have to switch windows in your zoom meeting just for this)

I'm wondering if we could printing stdout on the right side of the cells using a terminal-like window. the benefits are:

1. this would be explicit enough to show what is printed from stdout
2. it can be easily opt-out if there isn't any output to stdout from the cell

**Comment by cortner** [comment]
A variation on @Roger-luo proposal above: maybe there could be a flag for a cell (checkcox, some meta-data, ... not sure how to best specify that) that would open up such a `stdout` console in a convenient place next to or below or above the cell. 

I admit that I've found it quite surprising how well I managed with Pluto without stdout but every once in a while it does get frustrative.

**Comment by ederag** [comment]
For others interested in `@code_warntype` from Pluto, there's an imperfect workaround with
```julia
begin
	using Pkg;
	Pkg.add("PlutoUI")
	using PlutoUI
end
```
```julia
with_terminal() do
	f(x) = x == 1 ? 2 : 2.0
	@code_warntype f(1)
end
```

Currently (PlutoUI v0.7.6), the type instability is highlighted in upper case
![Screenshot_20210509_185529](https://user-images.githubusercontent.com/10962809/117580827-242a5a00-b0fa-11eb-9a30-95b18c313142.png)
while in the REPL the type instability is highlighted in red:
![image](https://user-images.githubusercontent.com/10962809/117580852-3d330b00-b0fa-11eb-8c78-00e04abe09d7.png)

But that might evolve, see https://github.com/fonsp/PlutoUI.jl/issues/88

**Comment by c42f** [comment]
I recently needed `@code_warntype` in pluto so I made a hack which I pasted at https://github.com/fonsp/PlutoUI.jl/issues/88#issuecomment-842079911.  This seemed to work fine, though it's certainly not the most elegant :)

**Comment by ForceBru** [comment]
Any progress on this? Pluto's package manager [has no problem outputting progress to Pluto](https://github.com/fonsp/Pluto.jl/wiki/🎁-Package-management#logs) - is it possible for a user to do this too?

**Comment by MichaelSchroter** [comment]
Hi I am trying to print "Hello World" in Julia Puto notebook. But it does not output anything. Print 

Code:

```print("Hello World!")```
```println("Hello World!")```

Runs. But does not produce an output. Would anyone be able help in this matter please?

Thanks & Best Regards
Schroter

**Comment by c42f** [comment]
> Would anyone be able help in this matter please?

The julialang discourse or Zulip would be a better place for this kind of question. To display text from a pluto cell, you can use

```
Text("Hello World!")
```
