### ISSUE TITLE
Pluto crashes on updating old Notebook

### ISSUE THREAD

**Issue by FelixBenning** [fonsp/Pluto.jl#2489]
# To report an issue, you need three things:
1. 📹 A video recording demonstrating the problem. (You can drag a video file into this box)

https://user-images.githubusercontent.com/29106652/222804811-12cda9dd-af11-40c7-aabc-6a0e76be1ff9.mp4

3. 📝 A short Pluto notebook file. (Upload the notebook file to https://gist.github.com/ and include the link.)

https://github.com/FelixBenning/optimization-review/commit/7ea43019d9c76032d5ceb0a1513929cc9d485721

4. 🤕 Try to clearly explain what the problem is, it might not be obvious to others! Instead of saying: "This does not work.", try to say: "I expected ..., but instead I am seeing ..."

When trying to run an old notebook, Pluto crashed. So I copied litereally every single cell from the old notebook into a new notebook. And the new notebook works (Git-diff above).

**Comment by fonsp** [comment]
It looks like the notebook was fixed because the new notebook uses updated versions of the packages you used: https://github.com/FelixBenning/optimization-review/commit/7ea43019d9c76032d5ceb0a1513929cc9d485721#diff-e8ce632fd65a5e61a3daab54ebd3c7bd9ab33cb819d1cbb35076e62c5e481a35L273-R276

You can also update packages without creating a new notebook: https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#updating-packages
