### ISSUE TITLE
Packages in Pluto notebook

### ISSUE THREAD

**Issue by dove88** [fonsp/Pluto.jl#2491]
Hi, I am trying to use the Pluto notebook and the DataFrame.jl package is already installed in my julia global environment. But whenever I try to import the DataFrame package in Pluto notebook, it's getting an error message that says 'DataFrame packed is not in my path'. Could you please advise me, how to use installed packages (global environment) in Pluto notebook without installing it again?

**Comment by Pangoraw** [comment]
Thanks for the report. Could you provide an example notebook with which we can reproduce the issue ? This could be caused by different things depending on whether or not you are using [Pluto's package manager](https://github.com/fonsp/Pluto.jl/wiki/%F0%9F%8E%81-Package-management#plutos-built-in-package-management).
