### ISSUE TITLE
Global variable becomes 'not defined' inside nested for loop

### ISSUE THREAD

**Issue by paulbthub** [fonsp/Pluto.jl#2568]
I'm using a global true/false variable called DONE to control flow through a 4-deep stack of nested for loops. This works fine for the first three levels (h1, v1, v2), but fails with a 'not defined' error inside the 4th level (v3).

This is a particularly strange bug because it's affected by code in the same cell that's never executed (try uncommenting line 328 in the last cell of the attached notebook and the same bug shows up 1 line earlier, ie at the `@debug "second checkpoint v3"  ANOTHER_GLOBAL` line instead of the `if DONE` line) and also by code in other cells -- which is why I'm also attaching two data (text) files: ~~if I set up this data from inside the notebook instead of reading it in from file, then the bug disappears(!)~~ no longer true: just use the smaller cleaner notebook instead

This also means that 1. the notebook can't be cleaned up much more than it already has been (otherwise the bug vanishes) and 2. ~~the two data files will need to be loaded into the same folder as the notebook for the bug to show up. (Otherwise it'll just produce a file error)~~ no longer true: just use the smaller cleaner notebook instead

I should also add that I've tried running this exact same code in Jupyter and it works as expected, so the problem really does seem to be somewhere in Pluto.

Pluto v0.19.25
Julia 1.8.5
Ubuntu 22.04
Firefox 113.0.1 64 bit

ETA -- here's a smaller, cleaned up notebook that doesn't need to read any external files but still reproduces the same 'not defined' error: 

https://gist.github.com/paulbthub/ef6dd5b7d59d88f94e4d0e22c00d67b1

notebook file -- (ETA: deprecated; better to use the smaller cleaner notebook linked above)
https://gist.github.com/paulbthub/2ea4230b8ca682c4e17411ae39ce91ee

two data files -- (ETA: no longer needed; just use the smaller cleaner notebook linked above)
https://gist.github.com/paulbthub/13185458f76d21c938f7dea1898ada01

video --

https://github.com/fonsp/Pluto.jl/assets/88824881/612a6013-36fb-4968-b7bd-08190adb49d6

**Comment by fonsp** [comment]
Can you make your notebook even smaller? Step by step, remove a chunk/line of code and run. If it still errors, continue, if not, Ctrl+Z. Also remove all comments and logs.

**Comment by fonsp** [comment]
😇 A general tip is to split long code into functions and definitions defined in separate cells. (And write little checks/tests for them!): any cell longer than 50 lines probably means that you should split functionality. Our advice is always: make more cells! Adding functionality? Add a new cell! Use Markdown to organize your code, and use little checks to show what code does. 

An example of this style is [this notebook](https://github.com/fonsp/Pluto.jl/blob/main/src/webserver/Firebasey.jl) (part of Pluto's internals). This could have been written as one giant loop with if-else switches, but lots of smaller chunks makes this notebook much more readable.

This will really help the feeling of "getting lost" in your code, and you don't need to keep so many things in your mental memory at once while coding. Later in your programming journey, it will also be really useful when you [collaborate with others](https://opensource.guide/how-to-contribute/)! It's much easier to read lots of little chunks, rather than one overwhelming block of code.

Rewriting into small chunks will not be easy at first! It takes more work than writing one big spaghetti code, but it will definitely save you time and energy in the long run :)

**Comment by fonsp** [comment]
This is an issue about soft/hard scope in Julia: https://docs.julialang.org/en/v1/manual/variables-and-scoping/

Pluto does not behave like the REPL, but it behaves like a standalone script. Your problem is that you create two variables, both named `DONE`: 
- one is created on line 108 https://gist.github.com/paulbthub/ef6dd5b7d59d88f94e4d0e22c00d67b1#file-waffle_global_bug_nofiles_cleaned-jl-L108
- another one (with the same name) is defined one line 381 https://gist.github.com/paulbthub/ef6dd5b7d59d88f94e4d0e22c00d67b1#file-waffle_global_bug_nofiles_cleaned-jl-L381

This second DONE is defined within the hard scope of the `for i in v3_start:12972` loop. So every reference to `DONE` within that loop refers to the variable defined on line 381. On line 330 you reference DONE, but it has not been defined yet.


**Solution**: instead of defining a `global DONE = false` (probably not what you want: do you want `DONE` to be used outside of this cell?), you can make it `local DONE = false`. Or even better: don't make the large cell a `begin` block, but a `let` block.

**Comment by paulbthub** [comment]
First, thank you for your comprehensive reply!  This clears up some misconceptions I didn't even know I  had about the scope of global vs local variables -- and also provides the solution to what you correctly guessed I'm trying to do, ie I can get DONE to exhibit the desired behavior by simply declaring it as a local variable at the highest level, or even not specifying 'local' at all, since that's the default.

Other points: Apologies for the state of the code. I know it's a mess -- and tbh I was embarrassed to post it. That said, unfortunately I don't think this kind of tree-search project -- where all 6 of the tree's branches work differently -- really lends itself to a functional approach at the flow control level. I'm hoping/expecting that in the end there will still be a bunch of shared, repeated, validity-checking code that I can put inside a function, but right now I'm just kludging my way through, and there are all kinds of broken, unused lines of nonsense that are still lying around. Ugh! And again, sorry about that.

And yes, there will be more cells! Absolutely!

As for indentations: yes! That bugs me too! But, at least on my desktop monitor, the code part of  the Pluto notebook pages only occupies about 5/8s of the total screen width. The right hand side of the page, except for when it's used for live docs and status,  is just blank, unused and unusable  white space, which means that after a few levels of nesting, the lines of code hit the right-hand margin, where they get broken up and wrapped around -- and they become very hard (for me) to read. The only way I've found to keep most of the lines from wrapping is to select chunks of code and haul them further to the left with ctrl [ .  But if there's a way to widen the code window so that it takes advantage of the entire width of the screen then that would be great! Please advise!

As to the original global vs local scope issue: yeah, I see that it's generated a lot of discussion over the past several years -- and now I can see why! It does seem strange and counterintuitive to me that a 'global' variable is only globally available at lower levels for *reading* while not being globally available for writing -- and that if you try to assign a new value to this global, then --  I dunno, Pluto?/Julia?/Julia but not in the REPL?/and not Julia in Jupyter nbclassic -- silently assigns the value to a new, 'shadow' variable with the same name without any kind of warning (although I seem to remember that Pluto used to have a very useful 'ambiguous scope' warning message? Maybe that message still appears under some circumstances?). Whereas to make a variable globally available at lower levels for both reading and writing, it has to be declared as (or left to default to) 'local'.

Also it doesn't help that the Jupyter nbclassic notebook does things differently. The following code produces different output in Pluto and nbclassic --

`begin
	global DONE = false
	for i in 1:2
		if 0!=0
			@info 1+1
		else
			DONE = "goodbye"
			@info "i loop" i DONE
			# DONE = "goodbye"

			for j in 1:2
				if 0!=0
					@info 1+1
				else
					# DONE = true
					@info "j loop" j DONE
					DONE = "parsnip"
				end
			end
		end
	end
	@info DONE
end`

The final DONE has a value of false in Pluto but "parsnip" in nbclassic. This seems to be a very unsatisfactory state of affairs.
