### ISSUE TITLE
IO reading problem when trying to import  MNIST datasets.

### ISSUE THREAD

**Issue by hungpham3112** [fonsp/Pluto.jl#2582]
## Step to reproduce:
- `using Pluto; Pluto.run()`
- Run this code in Pluto:
```
using LinearAlgebra, MLDatasets, Plots
MNIST()
```
- See the error.

## Environment:
OS: PopOS 22.0.4
Terminal: Alacritty v0.11.0
Julia version: 1.9.1
Pluto version: 0.19.26

## Videos:
[Screencast from 06-11-2023 06:03:22 PM.webm](https://github.com/fonsp/Pluto.jl/assets/75968004/5f84c9ef-b664-4db0-b6f2-88e0f079030b)

## Expectation:
Can download and import MNIST dataset normally.

**Comment by oxinabox** [comment]
I believe this is because Pluto (unlike jupyter) doesn't redirect reads to stdin into text-input fields.
Last time we talked about this, the response was that "won'tfix: People should use specal Pluto IO methods"
which to me is unsatisfying, since stdio is the lowest common demominator that works with the REPL, and it seems a bit much to expect a library author to be aware of the front-end IDE being used. 

The short term fix is to disable the prompt in DataDeps via `ENV["DATADEPS_ALWAYS_ACCEPT"] = "true"`

**Comment by Pangoraw** [comment]
Thanks for the report! Interactive use of stdin is not supported (see https://github.com/fonsp/Pluto.jl/discussions/765#discussioncomment-225226 for context).
To complement the great DataDeps specific answer from above, you can also replace stdin with a user controlled buffer locally if you wish to do so (maybe there is a Base function to do that already?):

![image](https://github.com/fonsp/Pluto.jl/assets/9824244/04fb4442-2689-411b-b7ae-2ade4bfe63ad)
