### ISSUE TITLE
Click "more" for embeddable element doesn't work

### ISSUE THREAD

**Issue by jbrea** [fonsp/Pluto.jl#2619]
The "more" button doesn't seem to work as expected (and reported in #1126) when embedded in an `@htl` block. It works normally for direct output.
[more_bug.jl.txt](https://github.com/fonsp/Pluto.jl/files/12188487/more_bug.jl.txt)
[more_bug.webm](https://github.com/fonsp/Pluto.jl/assets/12857162/ac47e995-75f9-4c12-a2f1-808acaef7707)

**Comment by disberd** [comment]
The problem also seems to appear within logs (e.g. `@info`) even without `@htl`:


https://github.com/fonsp/Pluto.jl/assets/12846528/56adef47-5cf2-4d51-8f59-88944011b7c0

**Comment by jbrea** [comment]
@disberd @Pangoraw Could somebody give me some pointers where to start to fix this bug? I guess the data is somehow not cached in the right js-variable, but I have little knowledge about Pluto internals and would therefore appreciate some input from a specialist.

**Comment by Pangoraw** [comment]
This is the code which gets called when More is clicked:

https://github.com/fonsp/Pluto.jl/blob/f297b127214ea7790b344b5c7687a21044c6323f/frontend/components/TreeView.js#L54-L57

which in turns calls the following Julia code:

https://github.com/fonsp/Pluto.jl/blob/83ec7c59661d672caa7e8be63049c9215bea14cf/src/webserver/Dynamic.jl#L488-L504

Now it makes sense for More in logs to not be working since reshow_cell only rerenders the output of the cell so the object id will always be unfound in the output. For the `@htl` problem, we have to look at whether or not the object ids are consistent when reshowing.

Here is the showmore handling in the actual renderer:

https://github.com/fonsp/Pluto.jl/blob/83ec7c59661d672caa7e8be63049c9215bea14cf/src/runner/PlutoRunner.jl#L896-L902

**Comment by jbrea** [comment]
Just noticed that 1d2c303 broke https://github.com/fonsp/Pluto.jl/blob/83ec7c59661d672caa7e8be63049c9215bea14cf/src/runner/PlutoRunner.jl#L2385 which relies on a two-argument `publish_to_js`. Does it make sense, if I try to track down the bug in a commit prior to 1d2c303 or should `Base.show(io::IO, m::MIME"text/html", e::EmbeddableDisplay)` first be fixed on main?

**Comment by jbrea** [comment]
Ah, in fact, the `@htl` example above works on master  with `const body = $(PublishedToJavascript(body));` instead of https://github.com/fonsp/Pluto.jl/blob/83ec7c59661d672caa7e8be63049c9215bea14cf/src/runner/PlutoRunner.jl#L2385
Is this the right way forward or will `PublishedToJavascript` be deprecated?

**Comment by disberd** [comment]
@jbrea I think the line you specifically referenced was something that was left unchanged (by mistake) on https://github.com/fonsp/Pluto.jl/pull/2608

The `publish_to_js` function previously accepted a 2-argument version while it does not anymore now.

I think the best way forward here is to have `const body = $(core_published_to_js(io, x))` as that is what internally is being called by the show method for `PublishedToJavascript`:
https://github.com/fonsp/Pluto.jl/blob/83ec7c59661d672caa7e8be63049c9215bea14cf/src/runner/PlutoRunner.jl#L2340-L2342

You could also use `PublishedToJavascript(body)` as you suggested but that is an un-necessary indirection. What is being deprected is the use of the function `publish_to_js` directly rather than the `PublishedToJavascript` struct.

`core_published_to_js` is the new API which should be used inside Pluto (and is called directly when showing PublishedToJavascript objects as seen above) and is also accessed by `AbstractPlutoDingetjes` for use in packages outside of Pluto (see https://github.com/JuliaPluto/AbstractPlutoDingetjes.jl/pull/11)
https://github.com/fonsp/Pluto.jl/blob/83ec7c59661d672caa7e8be63049c9215bea14cf/src/runner/PlutoRunner.jl#L2317-L2334

**Comment by jbrea** [comment]
Thanks, @disberd 

> const body = $(core_published_to_js(io, x))

I think this does not work, because of string interpolation. String interpolation of `PublishedToJavascript(x)` works, but the `io` there is the `io` of string interpolation, whereas the `io` in the above line refers to the `io` in `Base.show(io::IO, m::MIME"text/html", e::EmbeddableDisplay)`. I guess, going through `PublishedToJavascript` is still the best, no?

**Comment by disberd** [comment]
@jbrea you are probably right, didn't think about the interpolation directly on the string
