### ISSUE TITLE
Cells became inactive when switching between tabs and windows in Firefox

### ISSUE THREAD

**Issue by jmilo97** [fonsp/Pluto.jl#2694]
When I code into a Pluto.jl, and switch between tabs or windows, the current cell became inactive until I click on it again. I expect it to remain active, like any other webpage. A video recording is included, there is no need to upload Pluto notebook.
Thank you for your support :)

![pluto-issue](https://github.com/fonsp/Pluto.jl/assets/65023906/9a4b58b1-b805-442f-a903-64a8e1f34658)

**Comment by Pangoraw** [comment]
What is your Pluto and browser version? This seems similar to https://github.com/fonsp/Pluto.jl/issues/2518 which was fixed in Pluto@0.19.28.

**Comment by fonsp** [comment]
Hey @jmilo97! Was your issue fixed by updating Pluto?

I looked through your profile and I love your work!! Are you interested in submitting a [featured notebook](https://github.com/JuliaPluto/featured)? I think your [perculation visualisation notebook](https://jmilo.ir/percolation-julia/) would be a good fit, and we would be happy to feature a notebook written in Persian! (A notebook about anarchism, technology & education would also be awesome!)

Let us know if we can help you in any way with writing the featured notebook. We don't have much experience with Right-to-Left documents but we would love to support it better if we can, so please let us know if there are any RTL issues that we can improve! We would love to make Pluto and SciComp more accessible to people who do not speak english.

Send me an email if you're interested! fons@plutojl.org
