### ISSUE TITLE
The "Notify when done" checkbox can't be checked

### ISSUE THREAD

**Issue by yha** [fonsp/Pluto.jl#2809]
When checking it, it immediately unchecks.
![out](https://github.com/fonsp/Pluto.jl/assets/4170948/304f9c68-8f48-4416-ae00-65c3a7c0d846)
This video is on Edge on Windows. Also observed on Firefox and Chrome.

**Comment by fonsp** [comment]
Can you check your notification settings for this site (`localhost:1234`), for your browser, and your OS? Are you able to receive OS notifications from other sites?

Edge support page: https://support.microsoft.com/en-us/microsoft-edge/manage-website-notifications-in-microsoft-edge-0c555609-5bf2-479d-a59d-fb30a0b80b2b

**Comment by fonsp** [comment]
@yha Did this resolve your issue?

**Comment by fonsp** [comment]
I made https://github.com/fonsp/Pluto.jl/commit/15962d618c6120f1560e2b65c777d86a6b6ed6f4 which should make this situation more clear for other users :)

**Comment by yha** [comment]
> Can you check your notification settings for this site (`localhost:1234`)

Actually, I'm not running pluto on localhost, but on a server on a local network. Probably should have mentioned that, sorry for the confusion.
When running Pluto locally, the notification works. Remotely still doesn't work. 
I tried it now with the new Pluto version. I have notifications enabled for the server's address, but the checkbox won't change state and I get the new error message. On Edge and Chrome, when I try to enable notifications more specifically for `http://`+address it refuses because it's not secure (Firefox allows setting it, but the notifications still don't work). So perhaps the insecure connection is the issue? Is there a way to serve Pluto over https?

**Comment by ctrekker** [comment]
You're correct, several browsers don't permit notifications from insecure contexts ([see this MDN page](https://developer.mozilla.org/en-US/docs/Web/API/notification)).

Pluto doesn't support HTTPS hosting by itself since there are better tools to do this anyways. To my knowledge the best way to host Pluto in a secure context is with a reverse proxy like NGINX, but this requires lots of extra setup, not to mention the difficulties of actually getting an SSL certificate signed so browsers will accept a secure connection.
