### ISSUE TITLE
Precompilation problem on 1.11 with complete_remote_package

### ISSUE THREAD

**Issue by j-fu** [fonsp/Pluto.jl#2810]
See  https://gist.github.com/j-fu/1fd2a044636cf0a2737b999db043cc22
Pluto doesn't precompile on nightly, seen this in nightly ci for mac,linux, windows.

May be a problem with Julia, though.

**Comment by balenamiaa** [comment]
I think this is because [complete_remote_package](https://github.com/JuliaLang/Pkg.jl/blob/d267986c2d2100ad324cc67417c82e1f94114da5/ext/REPLExt/completions.jl#L55) is defined in an package extension of REPL now. It's used in [_registered_package_completions](https://github.com/fonsp/Pluto.jl/blob/c424619126afdbea3dd07f1cf27052aa01f52126/src/packages/PkgCompat.jl#L282). Replacing `Pkg.REPLMode` with `REPLExt` where 
```
using REPL
const REPLExt = Base.get_extension(Pkg, :REPLExt)
```
fixes it for me, but this seems like a hack.

**Comment by j-fu** [comment]
Yes, this indeed seems like a hack.
Did some research: in 1.10, `complete_remote_package` is in the REPLMode submodule, and not exported. Formally, then it  is not part of the public API.

Not sure if it make sense to code a work-around in Pluto now.

IMHO in 1.11 this could be made part of public API using the new `public` keyword. According to the logic of extensions, once it is public, `Pkg.jl` somwehre needs to declare 

```julia
public function complete_remote_package end
```
Then the extension would extend this function once REPL is loaded. 
IMHO this would warrant an issue or a PR with Pkg.jl .

**Comment by j-fu** [comment]
> const REPLExt = Base.get_extension(Pkg, :REPLExt)

Well, I just tried this out, the error as described in the gist persists.
The error occurs when calling `RegistryInstances.reachable_registries()` during precompilation: 

https://github.com/fonsp/Pluto.jl/blob/9f9ab2e1e858e978bcfe53f9ab2c28f2e547dfd9/src/packages/PkgCompat.jl#L170

I can call `RegistryInstances.reachable_registries()` from the REPL without problems. So there seems to be more to the picture, and we have at least two problems:
- fix the situation with `complete_remote_package`
- figure out what is going on with `RegistryInstances.reachable_registries()`
