### ISSUE TITLE
Method of callable type is stored with wrong name

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#288]
If i have some  

```struct Callable end```

and make it callable with 

```(calledobject::Callable)(x) = 5``` 

it seems that Pluto stores that method as a method of the function `calledobject` instead of the function `Callable`. At least when introducing another variable with that name

```calledobject = 2``` 

I get the following error:

```
Multiple definitions for calledobject:

Combine all definitions into a single reactive cell using a `begin ... end` block.
```

If i change the name of the calledobject argument like

```(calledobject2::Callable)(x) = 5``` 

everything works.

Here is a complete MWE:
```
### A Pluto.jl notebook ###
# v0.11.6

using Markdown
using InteractiveUtils

# ╔═╡ 87060500-de16-11ea-04b0-3d423b5e1f1e
struct Callme 
	callee
end

# ╔═╡ d29860b2-de16-11ea-0b0b-052667a78329
peter = Callme("Peter")

# ╔═╡ e1f5658c-de16-11ea-2762-f1751c337267
peter("Paul")

# ╔═╡ 9d282e1c-de16-11ea-3ddd-d5e6ab20f201
(c::Callme)(caller) = "Hi $caller, I am $(c.callee)"

# ╔═╡ f91e52da-de16-11ea-35de-47f8f60675ba
c = 5

# ╔═╡ Cell order:
# ╠═87060500-de16-11ea-04b0-3d423b5e1f1e
# ╠═9d282e1c-de16-11ea-3ddd-d5e6ab20f201
# ╠═d29860b2-de16-11ea-0b0b-052667a78329
# ╠═e1f5658c-de16-11ea-2762-f1751c337267
# ╠═f91e52da-de16-11ea-35de-47f8f60675ba
```

**Comment by karlwessel** [comment]
Thinking of it: this is kind of a feature, since otherwise I would have to define that method in the same cell as the `struct`. Can we have this feature for all methods? :grin:  (just kidding)

**Comment by fonsp** [comment]
Also see the alternative syntax in https://github.com/fonsp/Pluto.jl/issues/510

**Comment by DhruvaSambrani** [comment]
Same issue. In Packages like ReinforcementLearning.jl, function like objects are central. I'd love to help, but I have no idea 😅

**Comment by fonsp** [comment]
I wrote a test, this one should pass after the fix:

https://github.com/fonsp/Pluto.jl/blob/df353bf53871a00fd09481e773fe0f9ca5b96d57/test/ExpressionExplorer.jl#L278-L280

Instructions are at the top of that file.

**Comment by Pangoraw** [comment]
Hi! I took a quick look around this issue.

I don't quite understand why the `MyType` is in the assignment field in those tests. Doesn't it means that there will be two cells responsible for assigning to `MyType` (the struct declaration and the callable function declaration)?

Perhaps, we should keep it as a function declaration? Since `f() = ...` is already rewritten as `function f() ... end`. The two syntax will be handled in the same way by just rewriting from `(obj::MyType)(b, c) = ...` to `MyTypeAsCallableOrSomething(obj::MyType, b, c) = ...` (need to pick a better name though). The  `obj` being a parameter, it will not "leak" into the global namespace anymore.

The tests would then be (example fix at https://github.com/Pangoraw/Pluto.jl/commit/5c6dddd5d9154918b649aaafcaf65d7ac87fc835):
```julia
@test_broken testee(:((obj::MyType)(x,y) = x + z), [], [], [], [
  :MyTypeAsCallable => ([:z, :MyType], [], [:+], [])
]) 
@test_broken testee(:((obj::MyType)() = 1), [], [], [], [
  :MyTypeAsCallable => ([:MyType], [], [], [])
]) 
```
Let me know what you think!

**Comment by fonsp** [comment]
Hi @Pangoraw !

Sorry, I meant to add a comment about this but I forgot. You are right that this is not entirely correct, it is in fact a _workaround_ for this issue. 

Let's look at this example:
```julia
struct A x end
```
```julia
(a::A)(y) = a.x + y
```
```julia
apple = A(123)
```
```julia
apple(111) === 234
```

Here, cell 2 should run _after_ cell 1 (otherwise you get `UndefVarError: A`). But also:
- Changing and running cell 2 again should reevaluate anything that uses `A`, because they can eventually trigger the call.
- Deleting cell 2 should remove the callable property of `A`, and re-run cells that depend on `A`.

So, cell 2 should run after cell 1, but also, _dependents_ of cell 1 should run after cell 2.

### Workaround

This seemed difficult, so my workaround is to register cell 2 as a 'definition` of `A`. This forces you to combine cell 2 and cell 1 into a single cell (or you get a `Multiple definitions for A` error), which correctly handles the situation described above.



What do you think? Maybe we can find a solution that is 'semantically correct'? I think that the requirement to place cell 1 and cell 2 into a single cell is fine, but eventually we might want to turn Pluto.ExpressionExplorer into its own package, in which case we would want to stay close to semantic meaning without workarounds.

**Comment by fonsp** [comment]
To respond to your suggestion: it is actually very close to a solution. We could (internally) treat all function calls `f(1,2)` as references to both `f` and `fAsCallable`. That way, the cell `apple = MyType(123)` will reference `MyTypeAsCallable`.

The only situation not yet handled here is 2. from my previous comment. We might be able to resolve those, since we know that the deleted variable is a `*AsCallable`.

**How about:** we use my original hack (definition of `MyType`) right now to quickly fix the issue (or another suggestion), and we create a new long-term issue to rewrite it into something better?

**Comment by Pangoraw** [comment]
> it is in fact a workaround for this issue.

Ok, I thought the goal was to make the cell only dependant on `MyType`, making it a leaf in the dependency graph. Which would break reactivity for cell using the callable implementation. I think you're right about throwing an error for now if two separate cells have the definition and the callable. It gets tricky to implement the reactivity for the callable since an instance of `MyType` can be used in the callable implementation, creating a cyclic dependency:
```julia
julia> struct MyType x end

julia> b = MyType(10)
MyType(10)

julia> (obj::MyType)(y) = b.x + obj.x * y
#                         ^
#                         b used here
julia> b(10)
110
```

As for the fix itself, I propose that instead of renaming to `MyTypeAsCallable`, we simply rename to `MyType` and continue the exploration and since the struct itself will be defined as an assignment AND a function (in [ExpressionExplorer.jl#451](https://github.com/fonsp/Pluto.jl/blob/master/src/analysis/ExpressionExplorer.jl#L451)), the double definition will be detected. If the two are in the same cell then the function dependencies will be merged since it is the same name. The following test should pass: 

```julia
@test testee(:(begin struct MyType x::String end; (obj::MyType)(y) = obj.x + y; end), [], [:MyType], [], [
    :MyType => ([:String], [], [:+], []) # <--- Dependencies from both the callable and the struct
])
```
This fix still has room for improvement, mainly a clearer error message than "Multiple definitions for MyType.". 

Fix updated @ https://github.com/Pangoraw/Pluto.jl/commit/302481d3ae8de45365e35840d792c66e484e281d#diff-04c7252262a0e6de2db2cded7aba9b1130c1e5ba6adff25bf8ec3a34e36a4788R693-R694

**Comment by fonsp** [comment]
Great! Can you make a PR?

**Comment by Pangoraw** [comment]
> Great! Can you make a PR?

Sure! See PR #889 :wink:

**Comment by sbulcsu** [comment]
Hi! Have you thought about how to provide a clearer error message than "Multiple definitions for MyType."? It took me a while to find out what is the problem with my functor when using it in Pluto.
