### ISSUE TITLE
Using tmp for file storage can be insecure

### ISSUE THREAD

**Issue by garrison** [fonsp/Pluto.jl#294]
Says the "Getting started" notebook:

> The default location for new notebooks is /tmp

Storing files in `/tmp` can be a security problem, especially on a multi-user machine.  One example from https://owasp.org/www-community/vulnerabilities/Insecure_Temporary_File:

> On Unix based systems an even more insidious attack is possible if the attacker pre-creates the file as a link to another important file. Then, if the application truncates or writes data to the file, it may unwittingly perform damaging operations for the attacker. This is an especially serious threat if the program operates with elevated permissions.

In general, using the home directory is much safer.

**Comment by fonsp** [comment]
Using `tempdir()` instead of the home directory is a [conscious design choice](https://github.com/fonsp/Pluto.jl/issues/174) - Pluto is designed with quick experiments in mind. 

I did not know about this exploit, but it seems like the vulnerability of Pluto is very low, and similar to "normal Julia use", where it is common for packages and built-in functions to write to `/tmp`. (e.g. `Base.download`)

Pluto [chooses a filename that does not exist yet](https://github.com/fonsp/Pluto.jl/blob/v0.11.6/src/notebook/PathHelpers.jl#L39-L42) by numbering the filename, and it [`touch`es the file immediately afterwards](https://github.com/fonsp/Pluto.jl/blob/v0.11.6/src/notebook/PathHelpers.jl#L44). So the window in which an exploit needs to be done is extremely small (if possible at all), and it does not happen at a predictable time.

If I understand correctly, the exploit only exists for the situation where someone is running Julia as root (a known security issue), and the bad person is another user logged in on that same computer. Because of the rarity of that event, together with the check for file existence, I think that this vulnerability is too impractical and specific for us to worry about.

**Comment by garrison** [comment]
> similar to "normal Julia use", where it is common for packages and built-in functions to write to /tmp. (e.g. Base.download)

The docstring for `Base.download` says it downloads to a "randomly-named file in your temp directory."  There are also `mktempdir` and `mktemp` which are designed to handle temporary files securely.  `Base.download` uses `tempname`, whose docstring comes with a big Warning because of security concerns.  Do you know of places `Base.download` is used regularly and inappropriately?  If so, I would consider that a bug.  But at least the resulting file name is not predictable.

> Pluto chooses a filename that does not exist yet by numbering the filename

Then why is there a file called `'/tmp/sample Getting started.jl'` on my system?

> and it touches the file immediately afterwards.

It cannot be guaranteed that this happens "immediately."  It is a race condition.  System calls are often precisely where the kernel invokes a context switch.  These operations combined do not occur atomically.

> the exploit only exists for the situation where someone is running Julia as root

This is an incorrect understanding of how temporary files and user privileges work.  As your code demonstrates, any ordinary user can typically write to `/tmp`.

If you insist on storing files in `/tmp`, please use existing functions that are designed to do this securely, rather than rolling your own.  Does you code deal with race conditions correctly?  Does it result in a file with appropriate permissions set?  The best way to do this is to rely on code that already exists and has been designed to be secure.

**Comment by garrison** [comment]
This is fixed anyway by the closing of #265.
