### ISSUE TITLE
Allow using `Distributed`

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#300]
Pluto uses `Distributed` to create worker processes and to send Julia data structures between them. It works really well! And `Distributed` is pleasant to work with.

However, it means that _Pluto notebooks cannot use `Distributed`_, because your notebook's code is _executed on a slave process_ - you can't create processes, and you can accidentally control other running notebooks.

One solution is to run all your notebooks in the master process by setting the parameter:
```julia
import Pluto; Pluto.run(workspace_use_distributed=false)
```

But this makes the notebook server unresponsive while any notebook is running code, and the stop button is disabled.

## Solutions

What would a solution be? Should Pluto implement its own `Distributed`? This seems silly - we would get the most robust implementation by copying `Distributed`'s source code directly. Maybe there is a way to internally use a copy of `Distributed`? Copy the contents of `julia/stdlib/Distributed` into `/tmp`, rename `Distributed` to `DistributedCopy` and import that? But is the session state completely contained inside the package?

Is there a way to use `Distributed`, but with "multiple global sessions"?

Can we create a thin wrapper around `Distributed` and make sure that the Pluto process is using this instead? For example, `Distributed.add_procs()` would be `RealDistributed.remoteeval(Main, 1, :(RealDistributed.add_procs()))`. Will that also work for the packages that you import inside your notebook, that depend on Distributed?

**Comment by marius311** [comment]
Is there a reason why Pluto's workers need to be processes and can't just be threads? 

(Two other upsides of threads would be reduced memory usage and the ability to work with non-serializable objects.)

**Comment by fonsp** [comment]
Hmm. Can one thread interrupt another thread stuck in `while true end`? What happens when one thread segfaults?

**Comment by fonsp** [comment]
Can different threads use separate package environments? Can they load different versions of the same package?

**Comment by fonsp** [comment]
(Those aren't rhetorical questions 🙃 it's just that I have never used threads in Julia)

**Comment by Moelf** [comment]
jupyter notebook can do it because kernel is one process and jupyter notebook is running on a entirely separate (python) process.

I see two outs:
1. mimic jupyter and make each notebook a separate process and web UI tied to main session (so we can send SIGINT to each notebook still)

2. use main session as a worker broker, i.e when adding worker in a notebook, add at main process and 'shadow' / forward it to notebook worker

**Comment by carlocab** [comment]
> One solution is to run all your notebooks in the master process by setting an environment variable:
> 
> ```julia
> import Pluto; withenv(Pluto.run, "PLUTO_WORKSPACE_USE_DISTRIBUTED" => "false")
> ```

This workaround doesn't work for me, unfortunately. I'm still getting the same errors like `workspace3 not defined`, which is what would happen if I try to run Pluto normally but insist on `using Distributed`.

I guess it's not a big deal since this isn't the intended usage, but I thought it might be useful for you to know.

Thanks for the work you've put into Pluto!

**Comment by fonsp** [comment]
Some motivational words:

https://www.youtube.com/watch?v=nwdGsz4rc3Q

**Comment by lukeburns** [comment]
Workaround also fails for me. I get `@everywhere not defined` and `Distributed not defined` when I try to access it via `Distributed.@everywhere`. 

This behavior is unexpected:

<img width="339" alt="Screen Shot 2021-04-22 at 2 28 25 PM" src="https://user-images.githubusercontent.com/189068/115787541-388afa80-a377-11eb-8801-72fac9ec92ee.png">

<img width="397" alt="Screen Shot 2021-04-22 at 2 29 25 PM" src="https://user-images.githubusercontent.com/189068/115787546-3a54be00-a377-11eb-8991-9688797c2cea.png">

Why is this happening?

**Comment by lukeburns** [comment]
Quick and dirty workaround for `addprocs` and `@everywhere`, in case it's helpful to others.
```jl
### A Pluto.jl notebook ###
# v0.14.3

using Markdown
using InteractiveUtils

# ╔═╡ 797267f8-c7e6-4cb3-81d9-3ccc12956f56
begin
	macro everywhere(procs, ex)
		return esc(:(Main.@everywhere $procs $ex))
	end
	workers() = filter(pid -> pid != Main.myid(), Main.workers()) # exclude workspace process
	macro everywhere(ex)
		# have pluto handle evaluation on workspace process
		return esc(:(@everywhere workers() $ex; $ex))
	end
end

# ╔═╡ cfa09121-2457-42b1-9d20-e2518e7474e0
begin
	@everywhere 1 using Distributed
	addprocs(args...; kwargs...) = @everywhere 1 addprocs($args...; $kwargs...)
	rmprocs(args...; kwargs...) = @everywhere 1 rmprocs($args...; $kwargs...)
end

# ╔═╡ 6c0e0a11-3cc5-4ebe-b6f5-8df3e409cd05
@everywhere a = 2

# ╔═╡ ef45e5cc-cd10-4ad4-811a-9b767670dbf4
a^2

# ╔═╡ Cell order:
# ╠═797267f8-c7e6-4cb3-81d9-3ccc12956f56
# ╠═cfa09121-2457-42b1-9d20-e2518e7474e0
# ╠═6c0e0a11-3cc5-4ebe-b6f5-8df3e409cd05
# ╠═ef45e5cc-cd10-4ad4-811a-9b767670dbf4

```

**Comment by r-acad** [comment]
I am not sure if this is the right "thread" to ask about threads but:

- I start Julia with    ***julia -t 32*** and I see 32 threads (***Threads.nthreads()*** returns 32 in the REPL)
- I start Pluto and I only see 16 (***Threads.nthreads()*** returns 16 when run in a Pluto cell)

I solve a linear system in the REPL (***A\b***, where A is a dense matrix and b a dense vector) and I see all the cores running in parallel, but within Pluto I can only see one working in this case. 

In my code some sections seem to run in parallel and some others (which should be multithreaded) run on a single core.

Is this a limitation of Pluto or I am doing something wrong? (this is my first issue ever in Github so apologies if I made any etiquette mistakes :)

Raul

**Comment by fonsp** [comment]
Hey @r-acad !

Can you remove this question here and open a new one?

**Comment by r-acad** [comment]
Done, sorry, I', still learning :)

**Comment by Oblynx** [comment]
I wonder why Distributed can't nest. Is there any ongoing discussion with upstream?

**Comment by Oblynx** [comment]
You mention that
1. you can't create processes
2. you can accidentally control other running notebooks

If (2) is undesirable, we can use https://docs.julialang.org/en/v1/manual/distributed-computing/#Specifying-Network-Topology-(Experimental) like in https://github.com/fonsp/Pluto.jl/pull/1812

For (1), I wonder if it would be possible to launch independent Julia processes from each worker, instead of running the notebooks inside the process created by `Distributed.addproc`. This kind of encapsulation might be possible with a custom [`Distributed.ClusterManager`](https://docs.julialang.org/en/v1/manual/distributed-computing/#ClusterManagers).
Pluto uses the default `LocalManager` ClusterManager; however, by overriding the [`Distributed.launch`](https://docs.julialang.org/en/v1/stdlib/Distributed/#Distributed.launch) method, we could possibly do this.

**Comment by Oblynx** [comment]
I believe this issue is important because `Distributed` is part of Julia stdlib and supports a core paradigm of modern programming. It arguably has a high teaching value and can help "beginner" programmers to understand how to make use of modern computing infrastructure in a very high level way. IIUC, Pluto aims to facilitate prototyping of code that can be used in practice, and spawning processes or using `Dagger` is usually not just an optimization.

**Comment by fonsp** [comment]
Hi @Oblynx ! Thanks so much for your input, we really want this fixed! I fully agree that Distributed is essential to Julia's ecosystem, and also to beginners.

We have not posted much to this issue, but we have been regularly discussing this for a long time now. @dralletje has made a prototype of Pluto without distributed, but I think the performance hit was too big.

I did not bring this up at julia itself because I am quite intimidated by the problem, since I have little experience with distributed computing. I am also worried that the API of Distributed is not designed to handle a nested tree structure. 

Your approach sounds very promising! Going through the distributed codebase, I felt like a good approach would be to override some globals, simulating the PID=1 context on notebook processes. Creating a new `ClusterManager` sounds even better!

**Comment by dralletje** [comment]
![image](https://user-images.githubusercontent.com/767261/151046167-83e10f65-a3a2-4990-96b2-fbaca2e86283.png)

😏

**Comment by Oblynx** [comment]
:octopus: ! But how?

**Comment by fonsp** [comment]
Good news! We have a GSoC student working on **this issue** this summer! @savq

**Comment by schlichtanders** [comment]
Awesome to see progress with replacing Distributed!

As the GSoC is over, is there a further roadmap with next steps planned?

**Comment by fonsp** [comment]
Lots of progress happening in https://github.com/JuliaPluto/Malt.jl ! Take a look at https://github.com/JuliaPluto/Malt.jl/milestone/1

**Comment by fonsp** [comment]
We fixed it! 🎉

The fix is in #300, thanks to @savq (GSoC), @Pangoraw, @habemus-papadum and @pankgeorg!

# Test release

The upcoming Pluto release will start a testing period where Pluto still uses Distributed by default, but you can **enable Malt with**:

```julia
Pluto.run(workspace_use_distributed_stdlib=false)
```

Please try it out (`] add Pluto#main`) and give us your feedback!

**Comment by dralletje** [comment]
O MY GODDDDD

**Comment by schlichtanders** [comment]
Now that Distributed is able to be loaded, it seems it runs into the serialization problem reported here https://github.com/fonsp/Pluto.jl/issues/1030

so still no real use of Distributed till serialization is tackled?

**Comment by fonsp** [comment]
@schlichtanders Can you give an example?

**Comment by schlichtanders** [comment]
I was adding it to the other mentioned open issue https://github.com/fonsp/Pluto.jl/issues/1030#issuecomment-1755764431
> Now as Pluto supports the use of Distributed via Malt.jl, this issue appears again.
> 
> A simple remote call like
> 
> ```julia
> remotecall_fetch(() -> readchomp(`hostname`), pid) 
> ```
> 
> already gives the error like
> 
> ```
> UndefVarError: `workspace#72` not defined
> ```
> 
> I opened an issue on julialang/julia for this [JuliaLang/Distributed.jl#1](https://github.com/JuliaLang/Distributed.jl/issues/1)
