### ISSUE TITLE
[FR] keyboard shortcut for creating multiple cursors

### ISSUE THREAD

**Issue by haakon-e** [fonsp/Pluto.jl#3064]
Currently, (afaik) you can only create multiple cursors (mac) with `Option+click`, or by selecting some text, then `Cmd+D` to select matching text in the same cell (see e.g. #3063 for an example).

In VSCode, you can do `Option+Cmd+Down/Up-Arrow` to create cursors on the line below or above. I use this daily in VSCode, especially for data visualization work where you often define many similar variables, lines of code, etc. in the coding process. It would be great to add support for this, even if with another keyboard shortcut. Currently (in Chrome) the keyboard shortcut seems to switch between cursor focus on the webpage and the search bar, so perhaps it's challenging to oversteer that.

Julia v1.11, Pluto v0.20.0

**Comment by fonsp** [comment]
We can't override it, sorry!

**Comment by fonsp** [comment]
Hey! We have to prioritize issues since we don't have so much time... If there was an easy default to implement then fine, but it looks like we have to come up with our own shortcut, implement the codemirror functionality ourselves (it's not a built-in cm command like [copyLineDown](https://codemirror.net/docs/ref/#commands.copyLineDown)) and communicate it to the user. Too much work, sorry! :(
