### ISSUE TITLE
Option to disable retro console effect

### ISSUE THREAD

**Issue by zsunberg** [fonsp/Pluto.jl#3067]
Would it be possible to add an option to disable the retro console effect for `print`ed text? By "retro console effect", I mean the lighter and darker lines in this image that move slowly downward.

![image](https://github.com/user-attachments/assets/1893843a-034d-4e33-8cae-51f42445debe)

My interpretation is that someone added this to discourage use of `print` statements by making it seem more old-fashioned and clunky. I understand this, and it is fine to have it on by default, but this degrades the user experience by being very distracting when you do have to deal with printed output. Can we get an option to turn it off when we do need to examine printed output? :slightly_smiling_face:

**Comment by fonsp** [comment]
Hi @zsunberg !

There are always good alternatives to `print` statements, and Pluto's design should encourage that :) There won't be an option to turn of the visual effect, but there are many options to improve your code!

The **easy alternative** is to use `@info(...)` instead of `print`.

In your case, since your are displaying a **table**, you can create a table with `DataFrames` or similar, and output it in the cell. (You can also log it with `@info` to display the table during computation.)

If your goal is to display **grid-formatted text**, then check out the Julia `Text` function. If your Pluto cell returns a `Text` object, the string will be formatted monospace with original whitespace (without a retro effect).

**Comment by zsunberg** [comment]
I see, I didn't know that the logging functions like `@info` display differently. Thanks for the clarification.
