### ISSUE TITLE
Versioning the file format

### ISSUE THREAD

**Issue by fredrikekre** [fonsp/Pluto.jl#311]
I think it would be good to version the file format. I found some previous discussion about this in https://github.com/fonsp/Pluto.jl/issues/131#issuecomment-636764311

> First of all, I should say that we want to avoid any change to the file format, since this would mean adding conversion code to handle old files written before the format change - making the project harder to maintain.

which seems fair, but in the unfortunate case that the format has to change, it would be good to have the format recorded in the file. Pluto would just check that opened files has a format it understand, or error out, instead of adding conversion code.

**Comment by fonsp** [comment]
Right now it writes the Pluto version to the second line, I thought that this can be used to indirectly version the file format (if/when it needs to change).

Do you mean versioning it more explicitly? i.e. call this version 1, and change to 2 in the future?

**Comment by fredrikekre** [comment]
> Do you mean versioning it more explicitly? i.e. call this version 1, and change to 2 in the future?

Yea exactly, becuse presumable most (all?) Pluto versions can read the same file format? The reason I thought about this is that I thought about making Literate output pluto notebooks, and it would be good to have a specific spec (e.g. version 1) that I can output.

**Comment by fonsp** [comment]
I thought that the minor version number (minor while in `0.y.z`, major after `1.0.0`) could indicate the file format version. So then the current spec is `0.11`. I didn't plan on any changes to `0.12`, but `0.13` will include a package environment, which might require a change. (But I think we can write it in a backwards compatible way.)

You mentioned erroring instead of adding conversion code, but I do think that we should add conversion code on every change from now on. Otherwise you would have to start all your notebooks again. So in that spirit, outputting any current spec will work for all future versions.

**Comment by fonsp** [comment]
Let's revisit this if/when we ever need to change the format, or when VS Code wants to share the format @pfitzseb
