### ISSUE TITLE
support ? and ] REPL modes

### ISSUE THREAD

**Issue by stevengj** [fonsp/Pluto.jl#336]
It would be nice to support `?foo` to output the REPL docstring, and `] foo` to execute Pkg commands, similar to the REPL and IJulia.

`?` is implemented in IJulia [here](https://github.com/JuliaLang/IJulia.jl/blob/4fd955afa15c43af6f137e6d27a112958cc6f0e6/src/execute_request.jl#L83) — you just need to call `REPL.helpmode(text)`.  `]` is implemented in IJulia [here](https://github.com/JuliaLang/IJulia.jl/blob/4fd955afa15c43af6f137e6d27a112958cc6f0e6/src/execute_request.jl#L68-L71)

**Comment by fonsp** [comment]
`?foo` is supported!

**Comment by fonsp** [comment]
`]` won't be supported, I have some more ambitious plans - https://github.com/fonsp/Pluto.jl/issues/142#issuecomment-638481407 (more info is coming)

In the meantime you can do:
```julia
using Pkg
```

```julia
pkg"add PlutoUI@0.6.1"
```

**Comment by fonsp** [comment]
`?` is there because it is very commonly requested, but all it does is pop up the actual documentation UI or tell you that your browser window is to small to do so.

But cells that start with `?` or `]` are _not legal Julia code_ - if you use one in your notebook, then your notebook file is no longer an executable Julia script.

For `?` - it does not show the docs when you _run&save_ that code (which would just give an error), it pops up the docs when you enter the `?` character, and it starts searching while you type something after it.

**Comment by stevengj** [comment]
> But cells that start with ? or ] are not legal Julia code - if you use one in your notebook, then your notebook file is no longer an executable Julia script.

You could save it as some comment-encoded text like `#?# ...` and `#]# ...`, no?

**Comment by fonsp** [comment]
Yes but then Pluto needs to do code transforms, which it doesn't do yet.

I think the current `?` is nice, even better than waiting for the cell to be executed.

Once we have a built in package manager, we can do the same with `]` to pop up information/UI about packages.

**Comment by stevengj** [comment]
In Jupyter you can also do "shift-tab" and you will get pop-up help for the identifier by the cursor; I guess you could do the same in the sidebar.

**Comment by fonsp** [comment]
I guess that Pluto already has that, but it happens on every keystroke, right?
