### ISSUE TITLE
Stabilize and document Pluto backend API

### ISSUE THREAD

**Issue by non-Jedi** [fonsp/Pluto.jl#345]
I briefly started to look into what it would take to develop a Pluto frontend in emacs, but I'm not sure to what extent the websocket API is considered stable. Is it covered by semver? Documentation of the API would also of course be helpful, but it's less important than knowing that the API is stable or will at least provide backwards compatibility.

The other point of awkwardness I noticed right away is that there's no API for creating a new notebook. Instead you have to GET `/new` and then parse the URL you're being redirected to. This isn't too hateful to implement, but GET being stateful makes me a little uncomfortable.

**Comment by non-Jedi** [comment]
As a point of curiosity, why did you decide to basically implement request/response semantics on top of websockets instead of just using HTTP?

**Comment by fonsp** [comment]
It's not stable 😬 I change/add endpoints around quite often

> As a point of curiosity, why did you decide to basically implement request/response semantics on top of websockets instead of just using HTTP?

It used to be all REST, but websockets have much better ping time, because the connection persists and the header is smaller. The ping time is quite important - lots of actions like adding a cell, folding a cell, etc, all make a round trip before you see the effect in your browser. For some actions it's several round trips.

The reason for these round trips is to make the Julia backend handle all state transitions, and every browser blindly follows that state. This means that Pluto works with multiple clients at the same time, and everything is synchronized. (A feature that's much too hidden to be appreciated 😊)

Bound sliders and timers really push this ping time to its limit.

This explains the second reason: the server needs to send unrequested updates to all clients. This doesn't work with the traditional REST philosophy, so we used to do [HTTP long polling](https://en.wikipedia.org/wiki/Push_technology#Long_polling) but at some point you are just reimplementing websockets yourself.

**Comment by fonsp** [comment]
You're right about stateful `GET /new`, oops

**Comment by fonsp** [comment]
Let's have a video call sometime? fonsvdplas@gmail.com

**Comment by non-Jedi** [comment]
>It's not stable 😬 I change/add endpoints around quite often

I'll leave this issue as at least a long-term feature request then. Totally makes sense to iterate rapidly and not nail things down until you have a design you're really happy with.

Totally makes sense on the websocket justification. I hadn't gotten deep enough into the code to see any server-initiated notifications yet.

I'll send you an email.
