### ISSUE TITLE
Global and Local Scope inside the for and while loop

### ISSUE THREAD

**Issue by Dsantra92** [fonsp/Pluto.jl#379]
The notebook throws a `UndefVarError`  while accessing the global variables inside the for loop.
![error_log](https://user-images.githubusercontent.com/55111154/92412862-2a32fa00-f16b-11ea-9286-9f5b8e576021.png)

**Comment by shashankp** [comment]
Its not an issue with the for loop as such

![image](https://user-images.githubusercontent.com/498813/92525792-15756580-f242-11ea-8b95-21f12e424fc4.png)

**Comment by fonsp** [comment]
You need to keep all assignments and modifications (`+=`) within a single cell - otherwise reactivity can't work.

So:
```julia
begin
	s = 1
	for i in 1:10
		s += i
	end
	s
end
```

but this still won't work, because `for` **introduces a scope**. If you assign to `s` within the `for` loop, then you are assigning to a local variable, also called `s`, that is only defined within that loop. If you want to read more, this is called an _ambiguous assignment inside a soft scope_:
https://docs.julialang.org/en/v1/manual/variables-and-scoping/#Local-Scope

The solution is to use `local`:
```julia
s = begin
	local s = 1
	for i in 1:10
		s += i
	end
	s
end
```

or:

```julia
s = begin
	local my_s = 1
	for i in 1:10
		my_s += i
	end
	my_s
end
```

But `for` and `while` loops have so-called "functional" alternatives. The big ones are `map`, `filter`, `reduce` and `sum`:
```julia
begin
	s = 1
	s += sum(1:10) do i
		i
	end
end
```

Functional programming works very nicely together with Pluto - try it out!

**Comment by fonsp** [comment]
Sorry for all that strange syntax!

**Comment by Dsantra92** [comment]
@fonsp thank you for this wonderful clarification.
