### ISSUE TITLE
Watch external file modifications

### ISSUE THREAD

**Issue by kosiakk** [fonsp/Pluto.jl#426]
I'd like to edit the file outside of Pluto and see the changes reflected in the Web UI.  It is especially tempting 

Use-cases:
- External editors like VS Code if the notebook is incuded into another program due to its awesome simple file format.
- Changing Git branch.
- Two Pluto instances opening the same file unexpectedly.

Currently Pluto simply overwrites the file with an in-memory copy, not even checking that there is a conflict.

I guess, `FileWatching.poll_file` can help. In this case we might parse that new version of the file (as in Open) and try resucing computed results for the cells with the same ID and exactly the same contents. The rest can be deemed _modified_ and will re-compute upon Ctrl-S

**Comment by Moelf** [comment]
up vote for this one since `pluto` notebook is just a `.jl` this is very nice to have when you have to, say, rename/edit a long function from `vim` or something.

**Comment by fonsp** [comment]
#240

**Comment by pleiby** [comment]
#240 call for automatic reload whenever the file is changed on disk, but even that it would be beneficial if 
the user could easily _manually reload_ from file. That would address the two use cases which are necessitated by 
other intentional user activity:

- after user edits of the .jl file with a text editor (e.g. refactoring, global search and replace, fast moves, block deletes, etc)
- after source code updated on disk from a Git branch or pull

As it stands, even the following steps fail to read the updated code from the file.  
- backing up with the browser (<-) and 
- then typing the file path in the New session: Open from File dialog box 
Rather it uses some cached version of the file in memory.

Thanks for Pluto!

**Comment by Moelf** [comment]
@pleiby https://github.com/fonsp/Pluto.jl/issues/240#issuecomment-754851659 that's I thought too, haven't got around it but it's still in my mind
