### ISSUE TITLE
Notebook without cells

### ISSUE THREAD

**Issue by lukavdplas** [fonsp/Pluto.jl#444]
Pluto generally prevents you from creating notebooks with no cells, by making a new cell when you delete the last one. This makes sense, since there is no reason to have a notebook with no cells.

However, I noticed that to create an empty notebook by holding backspace in the only cell. After the cell disappears, my browser interprets the backspace as a shortcut to go to the previous page (the pluto menu). So I leave the notebook before the new cell is created. This is something that a user (like me) can do on accident.

Opening an empty notebook while it is still running gives an unusable notebook, since there is no button to create new cells. Opening after shutting it down results in a MethodError. Either way, not great.

It might be good to make sure that empty notebooks are loaded properly (by adding an empty cell to the notebook on loading). However, a more robust way of preventing empty notebooks would also solve the problem.

**Comment by shashankp** [comment]
Related to updating the backspace behaviour ?
https://github.com/fonsp/Pluto.jl/issues/408

**Comment by ekzhang** [comment]
If this helps: I accidentally just reproduced this bug and permanently corrupted a notebook - the steps were:

- Make at least 2 cells
- Ctrl+A (select all)
- Delete (delete cells, or press the "X" button)
- Confirm "Ok"

![image](https://user-images.githubusercontent.com/7550632/93728865-8e03ec80-fb87-11ea-8002-36b44ddadc98.png)

You end up with a blank screen. Surprisingly, this doesn't happen when only one cell is deleted - it only happens when there are >=2 cells deleted at the same time.
