### ISSUE TITLE
One-dimensional arrays lose relevant info in display

### ISSUE THREAD

**Issue by timholy** [fonsp/Pluto.jl#461]
In the REPL:
```julia
julia> using OffsetArrays

julia> kernel = OffsetArray([0.2, 1, 0.3], -1:1)
3-element OffsetArray(::Vector{Float64}, -1:1) with eltype Float64 with indices -1:1:
 0.2
 1.0
 0.3
```

In Pluto:
![image](https://user-images.githubusercontent.com/1525481/93708866-4f2a5400-faff-11ea-8a11-9113996c1ea9.png)

which doesn't reveal that the first element is accessed as `kernel[-1]`.

**Comment by timholy** [comment]
It also seems odd to me that ranges are displayed as lists.

**Comment by fonsp** [comment]
In this case, you will see the indices when you click, but I agree that we should differentiate between different `AbstractArray`s. Any ideas?

Maybe we can write it in the current form when it is an `Array{T,1}`, and write it as:
```julia
OffsetArray(::Vector{Float64}, -1:1)([0.2, 1.0, 0.3])
```
for other types?

**Comment by timholy** [comment]
How is the display done? For 2d arrays it seems to use the normal display machinery, but 1d seems different.

**Comment by fonsp** [comment]
1D abstractarrays, dicts, structs and some others use our custom display system, which is an interactive tree viewer.

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/issues/27

**Comment by fonsp** [comment]
New behaviour:

![image](https://user-images.githubusercontent.com/6933510/94028637-4d40e900-fdbc-11ea-88bd-1070faedc512.png)

**Comment by fonsp** [comment]
I also added a `: ` between the type and the array for `AbstractArray`s that are not `Array`s, like the `OffsetArray`, to differentiate an offsetarray from an `Array` of offsetarrays :)

**Comment by timholy** [comment]
Oh, that's very sweet! Thanks so much!

**Comment by thchr** [comment]
I was trying out Pluto and was surprised to find that if I define my own type as a subtype of `AbstractVector`, say, then Pluto will ignore any custom `Base.show` methods I define for that type and *always* just go via the `AbstractVector` show method.
I think there are lots of types that are useful to define as subtypes of `AbstractVector` while still having the ability to differentiate the display (e.g., if there is extra structure or metadata in the type).

As a silly example, which of course is not of any real applicability:

![image](https://user-images.githubusercontent.com/26799210/109078411-4ac81f80-76cb-11eb-9ef4-7301a9a69f66.png)

AFAICT, displaying `B` throws because it tries to go via `show(::IO, ..., ::AbstractVector)` rather than `show(::IO, ..., ::B)` which won't work since I didn't define the appropriate `AbstractVector` interface for `B` (but that's not the point, obviously).
