### ISSUE TITLE
Maximum figure width?

### ISSUE THREAD

**Issue by mlg556** [fonsp/Pluto.jl#541]
While displaying plots (with Plots, using the `size=(w,h)` argument) it seems that after about a value of 700 for the width, the figure gets cropped and a scrollbar is added. There is no such restriction on height, and I wish I could use more real estate on the screen for bigger plots, since most of the side bars in Pluto are blank anyway, but it seems that the maximum figure width allowed is the cell width. Can I change this behaviour?

![image](https://user-images.githubusercontent.com/26349315/95374323-db51bf00-08e6-11eb-9842-7ebf7ddbb2ec.png)

**Comment by Pocket-titan** [comment]
Hi! I can see two solutions from the top of my head:

## 1. Make all cells wider (respect plot size)
This will allow all cells to take up more space (which you might like, or not). The provided `size` parameter is respected.
```julia
html"""
<style>
  main {
    max-width: 900px;
  }
</style>
"""
```

## 2. Scale plot down (respect cell size)
This scales the plot down (while preserving its aspect ratio) to fit the cell. The provided `size` parameter is _not_ respected; the plot will be `<=` the provided `size[1]`!
```julia
html"""
<style>
  svg {
    width: 100%;
  }
</style>
"""
```

If one of these doesn't fit your needs, I can probably figure out another one (I'm thinking CSS grid style). Hope this helps!

![free-real-estate](https://user-images.githubusercontent.com/4435990/95452658-e1d54a80-0969-11eb-9cbd-bb1706f5768c.jpg)

**Comment by mlg556** [comment]
thanks @Pocket-titan  seems like solution 1 is what I need. is there any documentation that missed on this? I did not know that cell configuration was possible using raw html. perhaps this should be explained in a "configuration" section or something ?

**Comment by Pocket-titan** [comment]
I don't think you missed anything, it's just something that happens to work because of the way `html` elements are handled & css selectors are scoped (for example on [observable](http://observablehq.com), any css you return will be applied to the cells only. In Pluto it's applied to the entire document, which enables cool things like this!)
You're right that this could be explained better! That would maybe also reduce the number of issues relating to specific css things, because users can just change it themselves and get on with their life. I'll see what I can do, thanks for your suggestion 😊

**Comment by dralletje** [comment]
Also note that we are looking at scoping css by default, and then having a separate type for global css.
Something like

```julia
PlutoUI.PlutoHTML"""
<style>
  svg {
    width: 100%;
  }
</style>
"""
```
