### ISSUE TITLE
TypeError: Cannot read property 'startsWith' of null

### ISSUE THREAD

**Issue by garrison** [fonsp/Pluto.jl#544]
Since upgrading to v0.12.0, I regularly get the following Javascript alert:

![pluto-error](https://user-images.githubusercontent.com/91987/95396027-f2d07e00-08cd-11eb-93c4-20f8e70a8cbd.png)

I'll work on reducing to a minimal reproducible example, if I can.

**Comment by dralletje** [comment]
That is unfortunate, also because that error is quite "in your face" 😂

Can you try installing from github? I just pushed a possible fix and would love to see if it works before making another release.

Also if it happens again (and we should put this in the alert if we keep it) can you open your javascript console and give me the last logs there?

**Comment by garrison** [comment]
Looks like this is included in v0.12.2 now.  I've upgraded just now and have not experienced this error yet.  It used to occur when notebooks were loading, so I believe it is indeed fixed.  Closing, and will re-open with more information if it presents itself again.  Thanks!
