### ISSUE TITLE
Please don't print banner

### ISSUE THREAD

**Issue by musm** [fonsp/Pluto.jl#548]
Please don't print the Pluto banner, it's obtrusive during Pkg operations and is the only Pkg that decides to print such messages during load time 
![image](https://user-images.githubusercontent.com/4319522/95476904-c82a0800-0955-11eb-8880-3c17b0484373.png)

**Comment by fonsp** [comment]
You can disable it: https://github.com/fonsp/Pluto.jl/blob/v0.12.2/src/Pluto.jl#L53

**Comment by musm** [comment]
My suggestion is that it shouldn't be enabled on by default.

**Comment by musm** [comment]
Or rather it should only be printed in a REPL session or something similar, but as it is it just ends up polluting the printing of precompilation.

**Comment by KristofferC** [comment]
As a heads up, Pkg will soon automatically precompile packages when adding and updating packages and pretty print the progress. That will completely hide this message. I suggest moving it to `__init__`.

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/pull/389#issuecomment-689169113

**Comment by KristofferC** [comment]
You can use https://github.com/JuliaPackaging/Scratch.jl to store that you have printed it.

**Comment by fonsp** [comment]
Yeah that's nice! But we still support Julia v1.0 🙃

**Comment by Seelengrab** [comment]
How about only printing that on VERSION <= 1.5?

**Comment by mgkuhn** [comment]
Printing the banner at compile time has become a somewhat distracting first user experience since `Pkg` now routinely presents it during pre-compilation as “1 dependency had warnings”, as if something had gone wrong, possibly scaring new users:

```
  1 dependency had warnings during precompilation:
┌ Pluto [c3e4b0f8-55cb-11ea-2926-15256bba5781]
│  ┌ Info: 
│  │ 
│  │     Welcome to Pluto v0.19.27 🎈
│  │     Start a notebook server using:
│  │ 
│  │   julia> Pluto.run()
│  │ 
│  │     Have a look at the FAQ:
│  │     https://github.com/fonsp/Pluto.jl/wiki
│  └ 
└  
```

If we really need that banner at all, how about printing it from within `new_notebooks_directory()` called by `__init__()`, but only when `$JULIA_DEPOT_PATH/pluto_notebooks/` is created, and not printing it when that folder already exists? In other words, use the absence of that folder as a status indicator for whether this is a first-time module load.

That would preserve the once-only display that @fonsp wants, but also moves the banner out of precompilation.

**Comment by mgkuhn** [comment]
I've now implemented *two* alternative solutions for printing the Pluto banner only once, during module initialization, to make sure the banner no longer shows up during pre-compilation, where it is currently presented as a warning, which can scare new users.

* Method 1 uses the creation of `$JULIA_DEPOT_PATH/pluto_notebooks/` to record if a banner has already been shown. This is at  https://github.com/mgkuhn/Pluto.jl/banner1

* Method 2 uses [Scratch.jl](https://github.com/JuliaPackaging/Scratch.jl), as suggested above by @KristofferC. This is now PR #2628 

Having tried both, I now like Method 2 significantly better:
* It doesn't unnecessarily create `$JULIA_DEPOT_PATH/pluto_notebooks/`
* It records for which versions the banner has been shown already, thereby creating the possibility to show in future "What’s new" type messages below the banner as well.

Using Scratch.jl was previously dismissed because Pluto then still supported Julia 1.0, but this is now no longer the case, so I hope we can do this now.

Please have a look at PR #2628
