### ISSUE TITLE
Shortcut to run all selected cells

### ISSUE THREAD

**Issue by mossr** [fonsp/Pluto.jl#556]
Related to https://github.com/fonsp/Pluto.jl/issues/83, it would be nice to have a button or shortcut to re-run all cells. 

An example use case would be when changing a Plots.jl theme, it wouldn't trigger any cells with plots, so I'd have to manually mouse down to each cell and run them.

Thought? Sort of like Jupyter's "Run all cells", "Run all below", etc. 

<sup>(also, thank you for dealing with all of the bugs I encounter and my many feature requests 🤗)</sup>

**Comment by fonsp** [comment]
There's already a way to select all cells, we just need to add the ability to run every selected cell :)

**Comment by mossr** [comment]
Somewhat related: is there a *programmatic* way to run "submit all changes" from another cell?

Like calling `update_save_run!` but in a Pluto cell.

**Comment by lungben** [comment]
I second that this would be very helpful.
I sometimes end up in a notebook state from which it cannot recover automatically (usually when changing Pkg and PyCall related stuff), then I have to shut down the kernel and re-open the notebook again.

It would be great to have the equivalent of Jupyter's "Restart Kernel and Run all Cells" in Pluto, which should give the same results as closing and re-opening the notebook.

**Comment by fonsp** [comment]
(using the Shift+Enter shortcut)

**Comment by fonsp** [comment]
To clarify:

You can select all cells either using the selection box or using `Ctrl+A` when not focused on a cell:
![select edit multiple](https://user-images.githubusercontent.com/6933510/96363796-ab03ef00-1136-11eb-9acc-77f60405d283.gif)


You then press the play button (▶) on any of the selected cells, and they will all run in a single reactive batch, which is what you want.

I don't want to add a dedicated button for this because it's uncharming, but I would like the shortcut Shift+Enter to work in this case.
