### ISSUE TITLE
Failed to load notebook

### ISSUE THREAD

**Issue by ardsatcg** [fonsp/Pluto.jl#559]
sometimes can open, sometimes can't open, so ?

![Screenshot 2020-10-10 174153](https://user-images.githubusercontent.com/71117550/95651962-46d2a100-0b20-11eb-8ba3-d14aa24a21e4.png)

#559

**Comment by fonsp** [comment]
note to self: i think this is because of the space

**Comment by ardsatcg** [comment]
> note to self: i think this is because of the space

my C: spaces is 42.2 GB, it's less enough?

**Comment by dralletje** [comment]
I think @fonsp means the whitespace in the url :)

**Comment by ardsatcg** [comment]
> I think @fonsp means the whitespace in the url :)

i  don't get it, please give me an example😢

**Comment by dralletje** [comment]
Sorry for the confusion, hahaha :)

The url 
```
https://raw.githubusercontent.com/fonsp/Pluto.jl/master/sample/Basic mathematics.jl
                                                                    ^ right here
```
contains a space.
And spaces are really a pain in the ass sometimes :P
I fixed in in commit https://github.com/fonsp/Pluto.jl/commit/a87213291e7275193d78d5288e21db8246e65284
but until that works out, you can see use https://gist.githubusercontent.com/dralletje/f44e65ac9b59dede51b33a0b12fabbaa/raw/ae09b9fd6043fd66456ab1904ad222e7545ffd64/BasicMathematics.jl (this url does not have spaces)

**Comment by fonsp** [comment]
@dralletje I was unescaping URLs twice, fixed now: https://github.com/fonsp/Pluto.jl/commit/355edff7dca7cd2d420d923a7ab1d684e20a4c00
