### ISSUE TITLE
Input elements lead to too many cell evaluations

### ISSUE THREAD

**Issue by SteffenPL** [fonsp/Pluto.jl#567]
When input elements update, it seems to lead to unnecessary evaluations of the dependent cells before the correct values are used. See here:

<img src="https://user-images.githubusercontent.com/4634605/95757642-b1621900-0ca7-11eb-978c-2c96603c543e.PNG" width="600" />

I guess this is because first the HTML input element is created and the value set to missing and then a custom event is triggered by JS which updates the value. This short delay leads to an accumulation of unnecessary cell evaluations.

This effect accumulates if there are more input elements. In my notebooks, this leads to many delays and I have to trick Pluto to do the right things.

```julia
### A Pluto.jl notebook ###
# v0.12.3

using Markdown
using InteractiveUtils

# This Pluto notebook uses @bind for interactivity. When running this notebook outside of Pluto, the following 'mock version' of @bind gives bound variables a default value (instead of an error).
macro bind(def, element)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : missing
        el
    end
end

# ╔═╡ 207e5110-0b3a-11eb-28e8-49a8cfd287b9
begin 
	calls = []
	counter = [0,0,0,0]
end

# ╔═╡ 46f445e0-0b38-11eb-0e89-a1a1455d3e7e
begin 
	counter[1] += 1
	x_max = 19
end

# ╔═╡ 67731320-0c94-11eb-08f2-e3c266ba9018
begin
	counter[2] += 1
	@bind x HTML.body("""<input type="range" min="1" max="$(x_max)">""")
end

# ╔═╡ 124d36d0-0c96-11eb-2092-ff94f74d260d
begin
	counter[3] += 1
	@bind y HTML.body("""<input type="range" min="$(x)" max="$(x_max)">""")
end

# ╔═╡ 4a8b0132-0b38-11eb-1edc-ddcefb6783ee
begin 
	counter[4] += 1
	push!(calls, (x=x,x_max=x_max,y=y))
	z = x + x_max + y
	calls
end

# ╔═╡ d6701730-0c96-11eb-2901-294f39f9bab1
counter

# ╔═╡ Cell order:
# ╠═207e5110-0b3a-11eb-28e8-49a8cfd287b9
# ╠═46f445e0-0b38-11eb-0e89-a1a1455d3e7e
# ╠═67731320-0c94-11eb-08f2-e3c266ba9018
# ╠═124d36d0-0c96-11eb-2092-ff94f74d260d
# ╠═4a8b0132-0b38-11eb-1edc-ddcefb6783ee
# ╠═d6701730-0c96-11eb-2901-294f39f9bab1
```

**Comment by fonsp** [comment]
Looks like i broke this :)

**Comment by fonsp** [comment]
Thanks for the creative demonstration notebook by the way!

**Comment by fonsp** [comment]
(Read more about this in the Interactivity sample notebook.)

This is because you used `HTML.bdy("<input type=range>")` instead of a new `MySlider` type that has `Base.get(::MySlider) = initial_value` defined. So `@bind x HTML.body(...)` will set `missing` as its initial value for `x`, because it doesn't know what else to do.

Once the bond is rendered on the front-end, the browser parses the HTML, runs the input element and gets the initial value. This is sent back as the first bound value, and the dependent cell re-run.

---

PlutoUI has these default values set, and it also includes a `Slider`. Have a look at its source code to learn how it works!

**Comment by SteffenPL** [comment]
Thanks a lot, that makes perfect sense!
