### ISSUE TITLE
Automatically backup files created with old version

### ISSUE THREAD

**Issue by karlwessel** [fonsp/Pluto.jl#57]
When Pluto loads a notebook which was saved with an older version it already warns the user about it.

To avoid data loss it would be nice to automatically create a backup of that file before loading/changing it with a newer version.

Motivation: when Pluto 0.5.8 read a notebook that was saved with Version 0.5.4 it replaced it with an empty notebook :-)

**Comment by fonsp** [comment]
Whoops you noticed that we changed the file format, I wrongly assumed that we didn't have any users yet 🙃
From now on we will make sure that changes to the file format are rare, and backwards compatible.

I like your suggestion - let's do it!

Even better would be a _file format version_, since we plan on changing the format very rarely. This would prevent unnecessary backups.

**Comment by fonsp** [comment]
Better yet: create a backup, load notebook, save notebook, and compare new save and backup - if only the version numbers differ, delete the backup.

**Comment by fonsp** [comment]
[https://github.com/fonsp/Pluto.jl/blob/8489fc1851b591ae17b195acf6f3697180f1141d/src/notebookserver/Notebook.jl#L152-L173](https://github.com/fonsp/Pluto.jl/blob/8489fc1851b591ae17b195acf6f3697180f1141d/src/notebookserver/Notebook.jl#L152-L173) as described above

**Comment by karlwessel** [comment]
Sounds very good! Thank you for the quick implementation!
