### ISSUE TITLE
Julia WebAssembly backend

### ISSUE THREAD

**Issue by pankgeorg** [fonsp/Pluto.jl#572]
Web Assembly exists for this exact use case: client downloads a bundle and runs the whole Julia system within a wasm process.

That will make sharing work much easier since only data and assets will need to be hosted somewhere (no external computing power needed).

What do you think about that? I can investigate further if it makes sense to you.

**Comment by fonsp** [comment]
Last I checked, Julia isn't ready yet, but feel free to experiment. 

I believe that keno is the person driving wasm support, and he recently stated that he will work on it further and use Pluto as frontend: https://www.heise.de/news/Data-Science-Mozilla-stellt-webbasiertes-Tool-Iodide-ein-4918368.html

**Comment by dralletje** [comment]
https://keno.github.io/julia-wasm/website/repl.htm looks very cool though

**Comment by fonsp** [comment]
@pankgeorg Feel free to experiment and tell us what you found

**Comment by fonsp** [comment]
Running Pluto on WebAssembly would be a game changer - a huge leap in accessible and collaborative science! You could run & share notebooks entirely in the browser, without depending on a commercial service like google colab. To get there, we need to run Julia on wasm.

I talked with @keno, he is leading this development (https://github.com/Keno/julia-wasm) and he is excited to use Pluto as front-end for the first working demo. We could help him get there! Mainly:

### 1. Serious compiler business
keno told me that someone needs to dig into https://github.com/Keno/julia-wasm and get it running again with the up to date versions. Consider doing this in a nextjournal.com bash notebook so that others can reproduce.

### 2. Rewrite parts of Pluto to make it run in the browser. 
A first step would be to run the frontend standalone, with a JS interpreter as backend for example. This would make it possible to run a feature-incomplete julia-wasm already, non-reactively. This would be a good demo to get more attention.

---

If anyone is interested, let me know! It would be super super cool to get this going. We also have a small budget to pay you to work on this :) fonsvdplas@gmail.com if you are interested!

**Comment by fonsp** [comment]
I made a fork https://github.com/fonsp/julia-wasm with everything removed except a Julia runtime in the browser console
