### ISSUE TITLE
Blank frames make reactive Pluto plots look choppy

### ISSUE THREAD

**Issue by hdrake** [fonsp/Pluto.jl#577]
In the Julia REPL, you can use Plots.jl to make a plot on one line and update it in the next like
```julia
p = plot()
plot!(rand.(3,3), st=:heatmap)
```

Any additional calls to `plot!` will update the figure based on it's current state. However long it takes to evaluate a `plot!()` call, the old version of the figure will stay up until the new one replaces it. This is very convenient for interactive data exploration and for making animations.

![plot_REPL](https://user-images.githubusercontent.com/12971166/96183029-4feab600-0f04-11eb-82bb-0a47336540f6.gif)

In Pluto, however, users are encouraged to initialize plots in the same  (see the sample notebook [`Plots.jl`](https://github.com/fonsp/Pluto.jl/blob/master/sample/Plots.jl.jl) which says "I strongly recommend that you only use `plot!()` to alter plots you initialised in the same cell."). The problem is that the reactivity introduces some choppiness, which looks like a flash of empty white frames in between frames actually showing the plots.

![plot_Pluto](https://user-images.githubusercontent.com/12971166/96183945-b9b78f80-0f05-11eb-870d-9e96704ee28f.gif)

(Here's a snapshot of one of these white frames from my Gif-making app)
<img width="218" alt="Screen Shot 2020-10-15 at 4 30 18 PM" src="https://user-images.githubusercontent.com/12971166/96183983-c9cf6f00-0f05-11eb-8d36-77c19875352f.png">

Up to this point, it kind of makes sense because I can imagine there is a lag between when the empty plot in `plot()` is displayed up and when the updated results of `plot!(...)` are displayed. However, the same problem occurs even if you split the initialization of the figure `plot()` and updating `plot!()` into two separate cells.

![plot_Pluto_separate](https://user-images.githubusercontent.com/12971166/96184339-5e39d180-0f06-11eb-8f2f-7b43f90c3d2a.gif)

**Comment by fonsp** [comment]
Hi Henri!

I will have more time to look at this tomorrow, but in the meantime you can try to force the output to be SVG instead of HTML. Pluto has some choppiness-prevention-code, which only works if the old and new outputs are both images.

Paste this into the notebook:
```julia
as_svg(x) = PlutoUI.Show(MIME"image/svg+xml"(), repr(MIME"image/svg+xml"(), x))
```
and you use it like so:
```julia
let
	p = plot()
	plot!(p, ...)
end |> as_svg
```
or
```julia
let
	p = plot()
	plot!(p, ...)
	as_svg(p)
end
```


If PlutoUI.Show is not defined, then you will need to use the latest PlutoUI version in this notebook, which you can set up like this:
```julia
begin
	import Pkg
	Pkg.activate(mktempdir())

	Pkg.add([
		Pkg.PackageSpec(name="PlutoUI", version="0.6.7-0.6"),
		Pkg.PackageSpec(name="Plots", version="1"),
	])
	using Plots
	using PlutoUI
end
```

**Comment by hdrake** [comment]
Your fix works like a charm– thanks @fonsp!

**Comment by fonsp** [comment]
Some ideas:

## 1. check if the output is Plots.jl+GR and if so, use SVG instead of HTML
It is generally faster and solves this issue.

It does require some unfortunate code, but maybe the Plots.jl people are interested in adding it?

## 2. render HTML output to a "frame buffer", and only place it on the page after a small delay
Like in 3D graphics :)

This also isn't very nice, and it would make everything 1 frame slower. Maybe check if the HTML output is "large", and only delay it then?

## 3. find a way to document this problem+solution more clearly
The new `PlutoUI.as_mime` function might be interesting to more users, but on the other hand, it is exactly the kind of technobabble that Pluto should hide from users
