### ISSUE TITLE
Make the cell's runtime count up while the cell is running

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#636]

**Comment by pankgeorg** [comment]
I've implemented a front-end only solution that counts time since `Cell.js`'s becomes true.
That of course is wrong if you refresh the page, where still-running cells restart from 0. I think that showing the real time would need a timestamp provided from the backend (did a quick check and seems like the local `remote_code.timestamp` starts counting client-side).

If that sounds ok I can open a PR.

**Comment by fonsp** [comment]
Sure that sounds great! Also how would have done it - I did not think of the reloading situation.

**Comment by fonsp** [comment]
https://github.com/fonsp/Pluto.jl/pull/640
