### ISSUE TITLE
Can't ArrowDown on the last line if it wrapped

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#653]
![image](https://user-images.githubusercontent.com/6933510/98425684-682e9a80-2096-11eb-889c-eaf2acd083ca.png)

**Comment by zerefwayne** [comment]
Will take care of this! @fonsp

**Comment by zerefwayne** [comment]
On investigation :microscope:

1. Wordbreak is happening due to `.CodeMirror-line`'s CSS Property: `word-break: normal`. Which means we don't have control over wrapped lines through Javascript. It's all 1 single line for Javascript.

2. We need to find out the CodeMirror-line and divide it by character width to know the number of characters on a line. After that, we can calculate what line we are actually on and then move down accordingly.

**Comment by fonsp** [comment]
I'm sure that CodeMirror understands wrapper, otherwise it wouldn't be able to move the cursor to the right place if you press ArrowDown

**Comment by zerefwayne** [comment]
Nope, it doesn't work correctly. I tested this behavior. Here's a demo:

![cmdownbugdemo](https://user-images.githubusercontent.com/28949397/98853583-5a568c00-247f-11eb-9fe8-0c957371310f.gif)

Also, there's almost no mention of handling wrapping via codemirror in the documentation.

**Comment by zerefwayne** [comment]
@fonsp I dug into VS Code Editor's implementation to see how they do it. Surprisingly they are doing the same divide width by character width and then calculate position:

https://github.com/zerefwayne/vscode/blob/a48ad3b1d86eb653f9e0c18f925313cc0cd6d879/src/vs/editor/common/config/editorOptions.ts#L2250-L2253

**Comment by fonsp** [comment]
Fixed in https://github.com/fonsp/Pluto.jl/commit/a410fa8998315b0bc27ce777a7ff7bbc0f97b1fe

Here's how I check for wrapping:
https://github.com/fonsp/Pluto.jl/commit/a410fa8998315b0bc27ce777a7ff7bbc0f97b1fe#diff-6c16b38572dc31026a61d07cccade79268ca41902b3b3b35b1b17731e4362631R275
