### ISSUE TITLE
Anonymous function using `function(x)` unrecognised

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#654]
```julia
function image_skybox(img)
	f = function(position, skybox)
		lon = atan(-position[1], position[3])
		lat = -atan(position[2], norm(position[[1,3]]))

		get_index_rational(img, (lat/(pi)) + .5, (lon/2pi) + .5)
	end
	
	SkyBox([0.0, 0.0, 0.0], 1000, f)
end
```

gives

```
┌ Error: Failed to canonalize this strange looking function
│   ex = :((position, skybox))
└ @ Pluto.ExpressionExplorer ~/Pluto.jl/src/analysis/ExpressionExplorer.jl:827
```

**Comment by Pangoraw** [comment]
Hi! I took a look at this issue and I was wondering whether or not the defined function `f` should be in `symstate.func_decls` or defined as a variable?


### As a variable
Just a matter of fixing the `canonalize` function on anonymous functions https://github.com/Pangoraw/Pluto.jl/commit/85272788cac8e792c8ad2ea10332e248aec6d727.
```julia
@test testee(:(f = function(a, b) a + b * n end), [:n], [:f], [:+, :*], [])
```

### As a function
Allows us to use the duplicate methods detection but is a bit more complex https://github.com/Pangoraw/Pluto.jl/commit/81d97463bc42eea8a63b0d3962bd7b9b731c42e4.
```julia
@test testee(:(f = function(a, b) a + b * n end), [], [], [], [
       [:f] => ([:n], [], [:+, :*], [])
])
```

Because I went for case 2 first, I have the two fix implemented. Which solution is better ?
