### ISSUE TITLE
Pluto opens incorrect number of threads in edge case

### ISSUE THREAD

**Issue by czimm79** [fonsp/Pluto.jl#762]
The new update (#616) to start Pluto with all threads does not work for a CPU without hyperthreading/multithreading capabilities. For example, the Intel i7 9700k has 8 physical cores with 8 threads, but no hyperthreading. This results in only four threads being opened, when 8 are possible.

**Comment by z-m-k** [comment]
How about use `JULIA_NUM_THREADS`?

**Comment by disberd** [comment]
Commenting because I found myself wanting to change the number of Pluto threads but changing the `JULIA_NUM_THREADS` variable did not work on its own for me.
This can be achieved by passing the keyword arument `threads` as a string to the run command. Something like this for example was working in my case together with the env variable change.
`Pluto.run(;threads="$(Threads.nthreads())"`

**Comment by OliverEvans96** [comment]
It seems strange that the threads argument requires a string
