### ISSUE TITLE
Support DifferentialEquations.jl @ode_def

### ISSUE THREAD

**Issue by chengchingwen** [fonsp/Pluto.jl#781]
I'm trying to use Pluto to write some example with DifferentialEquations.jl. However, I got the error when I try to use `@ode_def` and define a variable with the same symbol present in the macro. Here is a MWE:

```julia
# in first cell: define the lorenz equation with `@ode_def`
lorenz! = @ode_def Lorenz begin
	dx = σ * (y - x)
	dy = x * (ρ - z) - y
	dz = x * y - β * z
end σ ρ β

# in second cell: define the parameters
begin
	σ = 10.0
	ρ = 28.0
	β = 8 / 3

	p = [σ, ρ, β]
end
```

In the above example, the first cell will run correctly alone. But if the second cell is present, the first cell will produce an error: 

```
lorenz!
      cannot assign a value to variable workspace86.Lorenz from module workspace88

top-level scope@Local: 129
```

**Comment by fonsp** [comment]
See #196

**Comment by donmcg** [comment]
I seem to be having the same basic problem with @ode_def.   In my case the variable bound to "hamHarOsc" doesn't play nicely.
But for fonsp the problem was the variable "Lorenz".   I notice it seems to have nothing to do with the second cell.  The error pops up on the second run of the macro.

Pluto accepts the initial run of the cell:

![initial](https://user-images.githubusercontent.com/183659/106217554-525ade00-618a-11eb-9604-f1eddf52de80.png)

But just run the same cell again and it has troubles:
 
![again](https://user-images.githubusercontent.com/183659/106217736-bed5dd00-618a-11eb-9e9d-f326619ad0d3.png)
