### ISSUE TITLE
Misaligned plots when plotting with UnicodePlots.jl using BrailleCanvas

### ISSUE THREAD

**Issue by tmthyln** [fonsp/Pluto.jl#870]
Certain plot types from [UnicodePlots.jl] do not plot correctly in Pluto (either using `with_terminal()` or not), as the characters are unaligned on the right side. This was originally discovered in [this Slack thread](https://julialang.slack.com/archives/C6E4SU1D3/p1611267421015000). We can see the issue just using the examples from the README:

```julia
using UnicodePlots
plt = lineplot([-1, 2, 3, 7], [-1, 2, 9, 4], title = "Example Plot", name = "my line", xlabel = "x", ylabel = "y")
```

![image](https://user-images.githubusercontent.com/32549553/105637733-e9e3c800-5e3c-11eb-9d3a-71e60d654442.png)

versus from the REPL:

![image](https://user-images.githubusercontent.com/32549553/105637971-34197900-5e3e-11eb-816c-96a884faba24.png)

In total, it looks like the following plot types are problematic:
* `lineplot`
* `scatterplot`
* `stairs`
* `spy`

(`heatmap` also doesn't work, but for a different reason relating to color display and not alignment.)

# Testing Configuration Details
Tested using Pluto v0.12.18 and UnicodePlots v1.3.0 on Chrome. It turns out Firefox has a similar issue but has a different vertical spacing:

![image](https://user-images.githubusercontent.com/32549553/105637883-d08f4b80-5e3d-11eb-96c6-e72d1d7d1ab0.png)

This looks to only a problem with the `BrailleCanvas` and a few spot-checked plots look fine using any of the other canvases.

# More Examples

![image](https://user-images.githubusercontent.com/32549553/105638455-b2771a80-5e40-11eb-819f-371dd9d1b341.png)
![image](https://user-images.githubusercontent.com/32549553/105638465-bf940980-5e40-11eb-834e-538698968af7.png)
![image](https://user-images.githubusercontent.com/32549553/105638477-ccb0f880-5e40-11eb-9364-4ac26db2cd40.png)

For convenience, here's a [Pluto notebook](https://gist.github.com/tmthyln/cfb12e4d96254565050e9617177d439f) that has the UnicodePlots.jl examples together.

# Cause

It looks like for whatever reason the Braille dot-0 (blank) character is being displayed as slightly wider than all the other characters in the browser, misaligning plots that use the BrailleCanvas.

![image](https://user-images.githubusercontent.com/32549553/105639349-ce30ef80-5e45-11eb-858b-bda64705b6df.png)

**Comment by tmthyln** [comment]
I have no solution yet<sup>1</sup>, but I willing to take this on (although I'm currently a bit busy, so it may be a bit of time before I can tackle this).

<sup>1</sup> There's the solution of just replacing all dot-0 characters with normal spaces, but I don't know if that would work for all plots without too many special cases, and would probably be more of a PR to UnicodePlots.jl to add a new show method for a new mimetype.

**Comment by pankgeorg** [comment]
Highly likely (but not sure yet) this is caused because a character or two from this set are not found in JuliaMono.
Chrome on Windows falls back on SegoeUI Symbol:
![image](https://user-images.githubusercontent.com/8681967/105648302-7335e180-5eb3-11eb-9c95-d0d04163f7fd.png)

I'll look at this with a priority (as I consider it an accessibility issue and not a package support issue)
Thanks for reporting (and linking a notebook!)

**Comment by pankgeorg** [comment]
The latest version of JuliaMono fixes the issue.

**Comment by cormullion** [comment]
I'm puzzled by this... 😂 I don't remember anything changing in this particular area of the font, and recent tests I did of UnicodePlots hadn't fixed this issue for me personally. I thought it was because the browser didn't render the Braille characters in the same way as the terminals do. But I'm happy if the issue has somehow fixed itself... 😀
