### ISSUE TITLE
Collect all initial bind values into a single call

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#928]
(internal issue)

```julia
# ╔═╡ a20bfeac-c3bd-4726-8ba2-e1af3e87539c
using PlutoUI

# ╔═╡ 21472529-e24d-4880-a2ce-acf4e24598f2
@bind x Slider(1:100)

# ╔═╡ b27878d5-444e-4dff-b1fd-a2433c5f62a4
@bind y Slider(1:100)

# ╔═╡ d2dae848-d03f-48e9-8e78-74d5a53b8bb9
md"""
It's the same if you use html inputs:
"""

# ╔═╡ 9a3bb8b6-721a-11eb-1f96-ef8691af6dfa
# @bind x html"<input type=range>"

# ╔═╡ ab5181a4-4d37-492e-be42-5646ab6cc9ba
# @bind y html"<input type=range>"

# ╔═╡ a29566f0-11f9-4172-9a94-055851a2282c
numberoftimes = Ref(0)

# ╔═╡ b7a05e7a-0e0a-4464-9635-aa364c828c5e
md"""
## When you refresh the page, the counter should increment **by zero**, not by two.
"""

# ╔═╡ f4fef5bd-1bd6-4ac8-824e-3ba2fb20bf78
let
	x
	y
	numberoftimes[] += 1
end

```

![image](https://user-images.githubusercontent.com/6933510/108407722-655e4c80-7224-11eb-9808-1cb64f17d049.png)

**Comment by dralletje** [comment]
This is kinda fixed now by https://github.com/fonsp/Pluto.jl/pull/975, but not because it is all in a single call now, but because the bonds won't be re-initialized when you refresh (like they used to before Firebasey). To make it one call, we need to make `set_bond_value_reactive` (https://github.com/fonsp/Pluto.jl/blob/master/src/webserver/Dynamic.jl#L403) take multiple bonds to update at once. The client->server state update is already in one request, but the mutator runs for all bonds one by one.

**Comment by fonsp** [comment]
Oh nice! I actually have already here https://github.com/fonsp/Pluto.jl/blob/bind-server-client-1/src/webserver/Dynamic.jl#L399

**Comment by dralletje** [comment]
Nice! Should I copy this over, or will bind-server-client-1 (reasonable soon) be merged into master? 🤔

**Comment by pankgeorg** [comment]
It is not bind-server related so no reason to wait I guess?

**Comment by fonsp** [comment]
I moved that code over to `main`: https://github.com/fonsp/Pluto.jl/commit/5ad1faf5039aef9532d4fd7c41d91a635341e89d
