### ISSUE TITLE
[Help welcome] Prevent file corruption

### ISSUE THREAD

**Issue by fonsp** [fonsp/Pluto.jl#952]
Currently, it is possible (but uncommon) that the notebook file gets corrupted. I have seen two reports about this, where someone had a broken notebook file after restarting Pluto. The problems were:
1. Pluto was interrupted during the write, only the first half of the notebook was saved.
1. The file looked like two notebook files were intertwined. It looks like two Pluto servers were saving to the same file simultaneously.

Any ideas on how we can prevent these types of issues? How do other editors prevent it?

**Comment by Pocket-titan** [comment]
Usually some kind of undo log (+ redo log) is used, something like this: http://www.cburch.com/cs/340/reading/log/index.html
but that doesn't look fun to implement cross-platform.
Maybe a good intermediate step: instead of immediately writing to the "real" file, write to a temp file, check if the checksum matches what we wanted to write, and only then overwrite the real file with the temp one? (and `finally` remove the temp file)

**Comment by Ellipse0934** [comment]
The simple way to do this is to first write to a another file ( say `.temp.pluto.xyz.jl` ) then perform an `fsync()` (Any buffers are guaranteed to be written to disk) and then finally rename the temporary file to the original file name.

However if there are plans for notebook collaboration where multiple people work on the same notebook then we may wanna look at [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type).

For the time being we can implement the first solution and if it's alright I can definitely have a go at it.

**Comment by Pocket-titan** [comment]
@Ellipse0934 `fsync` is posix though, right? then we'd have to split the file io based on OS, may be a bit of a headache but if you're up for it then I'd say go right ahead! 👍

unlikely we need CRDT's since (even with collab in mind) there's always a single server you connect to which manages the file io, which could resolve conflicts (apart from the fact that CRDT'S are *hard* & easy to implement badly)

**Comment by fonsp** [comment]
(This would be fixed by https://github.com/JuliaLang/julia/issues/39892, it might be worth to contribute this directly to Julia itself)
