### ISSUE TITLE
Printing issue with ASCII colour characters

### ISSUE THREAD

**Issue by chenspc** [fonsp/Pluto.jl#983]
I ran into a printing problem when using [Configuration.jl](https://github.com/Roger-luo/Configurations.jl) in Pluto. See also Roger-luo/Configurations.jl#18. The package author said 
> haha, this is because Pluto doesn't support ASCII color characters - would be nice if Pluto supports it. 

Is this something that will be added in the future, or are there any suggested workarounds? Thanks! 
<img width="957" alt="extra_characters" src="https://user-images.githubusercontent.com/10161227/110400256-3c84e680-806f-11eb-9a57-57924d9ec654.png">

**Comment by fonsp** [comment]
Hey! Pluto does not support ASCII color characters (since it is not a terminal), which we declare using the IOContext. We won't support color characters because we support HTML+CSS output.

Take a look at a very similar PR that I submitted https://github.com/SciML/SciMLBase.jl/pull/30. Note that for this PR, I tried to minimize code changes, but ideally you would use `Base.printstyled` or `Crayons.jl` to make this automatic. (At least, I assume that these handle the `:color` setting, I haven't tried it.)

In the particular case of Configurations.jl: Note that Pluto has a really nice built-in viewer for structs, which uses similar color and indentation, except you can collapse the tree. You might want to consider disabling the custom show method inside Pluto. (The official way is to use `isdefined(Main, :PlutoRunner)` to check for Plutoness)

**Comment by fonsp** [comment]
It looks like this is an issue with Crayons.jl -- it should check the `:color` setting.

**Comment by Roger-luo** [comment]
I haven't looked into this, but I'm thinking to provide a `show` method for HTML specifically which should solve this problem. 

On the other hand, we should file an issue for Crayons?
